"use strict";this.content_ads_contributor_ContributorGdprCachedJs=this.content_ads_contributor_ContributorGdprCachedJs||{};(function(_){var window=this;
try{
var aa=function(a){var b=0;return function(){return b<a.length?{done:!1,value:a[b++]}:{done:!0}}},ba=function(a){var b="undefined"!=typeof window.Symbol&&window.Symbol.iterator&&a[window.Symbol.iterator];return b?b.call(a):{next:aa(a)}},ca="function"==typeof Object.defineProperties?Object.defineProperty:function(a,b,c){a!=Array.prototype&&a!=Object.prototype&&(a[b]=c.value)},l="undefined"!=typeof window&&window===this?this:"undefined"!=typeof window.global&&null!=window.global?window.global:this,
da=function(a,b){if(b){var c=l;a=a.split(".");for(var d=0;d<a.length-1;d++){var e=a[d];e in c||(c[e]={});c=c[e]}a=a[a.length-1];d=c[a];b=b(d);b!=d&&null!=b&&ca(c,a,{configurable:!0,writable:!0,value:b})}},ea=function(){ea=function(){};l.Symbol||(l.Symbol=fa)},fa=function(){var a=0;return function(b){return"jscomp_symbol_"+(b||"")+a++}}(),ia=function(){ea();var a=l.Symbol.iterator;a||(a=l.Symbol.iterator=l.Symbol("iterator"));"function"!=typeof Array.prototype[a]&&ca(Array.prototype,a,{configurable:!0,
writable:!0,value:function(){return ha(aa(this))}});ia=function(){}},ha=function(a){ia();a={next:a};a[l.Symbol.iterator]=function(){return this};return a},m=function(a,b){return Object.prototype.hasOwnProperty.call(a,b)};
da("WeakMap",function(a){function b(){}function c(a){m(a,e)||ca(a,e,{value:new b})}function d(a){var d=Object[a];d&&(Object[a]=function(a){if(a instanceof b)return a;c(a);return d(a)})}if(function(){if(!a||!Object.seal)return!1;try{var b=Object.seal({}),c=Object.seal({}),d=new a([[b,2],[c,3]]);if(2!=d.get(b)||3!=d.get(c))return!1;d["delete"](b);d.set(c,4);return!d.has(b)&&4==d.get(c)}catch(r){return!1}}())return a;var e="$jscomp_hidden_"+Math.random();d("freeze");d("preventExtensions");d("seal");
var f=0,g=function(a){this.a=(f+=Math.random()+1).toString();if(a){a=ba(a);for(var b;!(b=a.next()).done;)b=b.value,this.set(b[0],b[1])}};g.prototype.set=function(a,b){c(a);if(!m(a,e))throw Error("a`"+a);a[e][this.a]=b;return this};g.prototype.get=function(a){return m(a,e)?a[e][this.a]:void 0};g.prototype.has=function(a){return m(a,e)&&m(a[e],this.a)};g.prototype["delete"]=function(a){return m(a,e)&&m(a[e],this.a)?delete a[e][this.a]:!1};return g});
da("Map",function(a){if(function(){if(!a||"function"!=typeof a||!a.prototype.entries||"function"!=typeof Object.seal)return!1;try{var b=Object.seal({x:4}),c=new a(ba([[b,"s"]]));if("s"!=c.get(b)||1!=c.size||c.get({x:4})||c.set({x:4},"t")!=c||2!=c.size)return!1;var d=c.entries(),e=d.next();if(e.done||e.value[0]!=b||"s"!=e.value[1])return!1;e=d.next();return e.done||4!=e.value[0].x||"t"!=e.value[1]||!d.next().done?!1:!0}catch(y){return!1}}())return a;ia();var b=new window.WeakMap,c=function(a){this.b=
{};this.a=f();this.size=0;if(a){a=ba(a);for(var b;!(b=a.next()).done;)b=b.value,this.set(b[0],b[1])}};c.prototype.set=function(a,b){a=0===a?0:a;var c=d(this,a);c.list||(c.list=this.b[c.id]=[]);c.l?c.l.value=b:(c.l={next:this.a,v:this.a.v,head:this.a,key:a,value:b},c.list.push(c.l),this.a.v.next=c.l,this.a.v=c.l,this.size++);return this};c.prototype["delete"]=function(a){a=d(this,a);return a.l&&a.list?(a.list.splice(a.index,1),a.list.length||delete this.b[a.id],a.l.v.next=a.l.next,a.l.next.v=a.l.v,
a.l.head=null,this.size--,!0):!1};c.prototype.clear=function(){this.b={};this.a=this.a.v=f();this.size=0};c.prototype.has=function(a){return!!d(this,a).l};c.prototype.get=function(a){return(a=d(this,a).l)&&a.value};c.prototype.entries=function(){return e(this,function(a){return[a.key,a.value]})};c.prototype.keys=function(){return e(this,function(a){return a.key})};c.prototype.values=function(){return e(this,function(a){return a.value})};c.prototype.forEach=function(a,b){for(var c=this.entries(),d;!(d=
c.next()).done;)d=d.value,a.call(b,d[1],d[0],this)};c.prototype[window.Symbol.iterator]=c.prototype.entries;var d=function(a,c){var d=c&&typeof c;"object"==d||"function"==d?b.has(c)?d=b.get(c):(d=""+ ++g,b.set(c,d)):d="p_"+c;var e=a.b[d];if(e&&m(a.b,d))for(a=0;a<e.length;a++){var f=e[a];if(c!==c&&f.key!==f.key||c===f.key)return{id:d,list:e,index:a,l:f}}return{id:d,list:e,index:-1,l:void 0}},e=function(a,b){var c=a.a;return ha(function(){if(c){for(;c.head!=a.a;)c=c.v;for(;c.next!=c.head;)return c=
c.next,{done:!1,value:b(c)};c=null}return{done:!0,value:void 0}})},f=function(){var a={};return a.v=a.next=a.head=a},g=0;return c});
var ja=ja||{},p=this,q=function(a){return void 0!==a},t=function(a){return"string"==typeof a},ka=/^[\w+/_-]+[=]{0,2}$/,la=null,ma=function(){},na=function(a){var b=typeof a;if("object"==b)if(a){if(a instanceof Array)return"array";if(a instanceof Object)return b;var c=Object.prototype.toString.call(a);if("[object Window]"==c)return"object";if("[object Array]"==c||"number"==typeof a.length&&"undefined"!=typeof a.splice&&"undefined"!=typeof a.propertyIsEnumerable&&!a.propertyIsEnumerable("splice"))return"array";
if("[object Function]"==c||"undefined"!=typeof a.call&&"undefined"!=typeof a.propertyIsEnumerable&&!a.propertyIsEnumerable("call"))return"function"}else return"null";else if("function"==b&&"undefined"==typeof a.call)return"object";return b},oa=function(a){return"array"==na(a)},u=function(a){var b=na(a);return"array"==b||"object"==b&&"number"==typeof a.length},v=function(a){return"function"==na(a)},pa=function(a){var b=typeof a;return"object"==b&&null!=a||"function"==b},qa=function(a,b,c){return a.call.apply(a.bind,
arguments)},ra=function(a,b,c){if(!a)throw Error();if(2<arguments.length){var d=Array.prototype.slice.call(arguments,2);return function(){var c=Array.prototype.slice.call(arguments);Array.prototype.unshift.apply(c,d);return a.apply(b,c)}}return function(){return a.apply(b,arguments)}},w=function(a,b,c){Function.prototype.bind&&-1!=Function.prototype.bind.toString().indexOf("native code")?w=qa:w=ra;return w.apply(null,arguments)},sa=Date.now||function(){return+new Date},x=function(a,b){function c(){} c.prototype=b.prototype;a.R=b.prototype;a.prototype=new c;a.prototype.constructor=a;a.X=function(a,c,f){for(var d=Array(arguments.length-2),e=2;e<arguments.length;e++)d[e-2]=arguments[e];return b.prototype[c].apply(a,d)}};
var z=function(a){if(Error.captureStackTrace)Error.captureStackTrace(this,z);else{var b=Error().stack;b&&(this.stack=b)}a&&(this.message=String(a))};x(z,Error);z.prototype.name="CustomError";var ta=Array.prototype.indexOf?function(a,b){return Array.prototype.indexOf.call(a,b,void 0)}:function(a,b){if(t(a))return t(b)&&1==b.length?a.indexOf(b,0):-1;for(var c=0;c<a.length;c++)if(c in a&&a[c]===b)return c;return-1},ua=Array.prototype.forEach?function(a,b,c){Array.prototype.forEach.call(a,b,c)}:function(a,b,c){for(var d=a.length,e=t(a)?a.split(""):a,f=0;f<d;f++)f in e&&b.call(c,e[f],f,a)},va=Array.prototype.some?function(a,b){return Array.prototype.some.call(a,b,void 0)}:function(a,b){for(var c=
a.length,d=t(a)?a.split(""):a,e=0;e<c;e++)if(e in d&&b.call(void 0,d[e],e,a))return!0;return!1},xa=function(a){a:{var b=wa;for(var c=a.length,d=t(a)?a.split(""):a,e=0;e<c;e++)if(e in d&&b.call(void 0,d[e],e,a)){b=e;break a}b=-1}return 0>b?null:t(a)?a.charAt(b):a[b]},ya=function(a,b){b=ta(a,b);var c;(c=0<=b)&&Array.prototype.splice.call(a,b,1);return c},za=function(a){return Array.prototype.concat.apply([],arguments)},Aa=function(a){var b=a.length;if(0<b){for(var c=Array(b),d=0;d<b;d++)c[d]=a[d];return c}return[]},
Ba=function(a,b){for(var c=1;c<arguments.length;c++){var d=arguments[c];if(u(d)){var e=a.length||0,f=d.length||0;a.length=e+f;for(var g=0;g<f;g++)a[e+g]=d[g]}else a.push(d)}},Ca=function(a,b,c){return 2>=arguments.length?Array.prototype.slice.call(a,b):Array.prototype.slice.call(a,b,c)},Da=function(a,b){for(var c=[],d=0;d<b;d++)c[d]=a;return c},Ea=function(a){for(var b=[],c=0;c<arguments.length;c++){var d=arguments[c];if(oa(d))for(var e=0;e<d.length;e+=8192)for(var f=Ea.apply(null,Ca(d,e,e+8192)), g=0;g<f.length;g++)b.push(f[g]);else b.push(d)}return b};
var Fa=function(a){for(var b=[],c=0,d=0;d<a.length;d++){var e=a.charCodeAt(d);255<e&&(b[c++]=e&255,e>>=8);b[c++]=e}return b};var Ga=String.prototype.trim?function(a){return a.trim()}:function(a){return/^[\s\xa0]*([\s\S]*?)[\s\xa0]*$/.exec(a)[1]},Ha=function(a,b){return a<b?-1:a>b?1:0};var Ia;a:{var Ja=p.navigator;if(Ja){var Ka=Ja.userAgent;if(Ka){Ia=Ka;break a}}Ia=""}var A=function(a){return-1!=Ia.indexOf(a)};var La="constructor hasOwnProperty isPrototypeOf propertyIsEnumerable toLocaleString toString valueOf".split(" "),Ma=function(a,b){for(var c,d,e=1;e<arguments.length;e++){d=arguments[e];for(c in d)a[c]=d[c];for(var f=0;f<La.length;f++)c=La[f],Object.prototype.hasOwnProperty.call(d,c)&&(a[c]=d[c])}};
var Oa=function(a){var b=Na;return Object.prototype.hasOwnProperty.call(b,9)?b[9]:b[9]=a(9)};var Pa=A("Opera"),Qa=A("Trident")||A("MSIE"),Ra=A("Edge"),Sa=A("Gecko")&&!(-1!=Ia.toLowerCase().indexOf("webkit")&&!A("Edge"))&&!(A("Trident")||A("MSIE"))&&!A("Edge"),Ta=-1!=Ia.toLowerCase().indexOf("webkit")&&!A("Edge"),Ua;
a:{var Va="",Wa=function(){var a=Ia;if(Sa)return/rv:([^\);]+)(\)|;)/.exec(a);if(Ra)return/Edge\/([\d\.]+)/.exec(a);if(Qa)return/\b(?:MSIE|rv)[: ]([^\);]+)(\)|;)/.exec(a);if(Ta)return/WebKit\/(\S+)/.exec(a);if(Pa)return/(?:Version)[ \/]?(\S+)/.exec(a)}();Wa&&(Va=Wa?Wa[1]:"");if(Qa){var Xa,Ya=p.document;Xa=Ya?Ya.documentMode:void 0;if(null!=Xa&&Xa>(0,window.parseFloat)(Va)){Ua=String(Xa);break a}}Ua=Va}
var Za=Ua,Na={},$a=function(){return Oa(function(){for(var a=0,b=Ga(String(Za)).split("."),c=Ga("9").split("."),d=Math.max(b.length,c.length),e=0;0==a&&e<d;e++){var f=b[e]||"",g=c[e]||"";do{f=/(\d*)(\D*)(.*)/.exec(f)||["","","",""];g=/(\d*)(\D*)(.*)/.exec(g)||["","","",""];if(0==f[0].length&&0==g[0].length)break;a=Ha(0==f[1].length?0:(0,window.parseInt)(f[1],10),0==g[1].length?0:(0,window.parseInt)(g[1],10))||Ha(0==f[2].length,0==g[2].length)||Ha(f[2],g[2]);f=f[3];g=g[3]}while(0==a)}return 0<=a})};
var ab=A("Safari")&&!((A("Chrome")||A("CriOS"))&&!A("Edge")||A("Coast")||A("Opera")||A("Edge")||A("Silk")||A("Android"))&&!(A("iPhone")&&!A("iPod")&&!A("iPad")||A("iPad")||A("iPod"));var bb=null,cb=null,db=null,eb=Sa||Ta&&!ab||Pa,fb=eb||"function"==typeof p.btoa,gb=eb||!ab&&!Qa&&"function"==typeof p.atob,ib=function(a,b){hb();b=b?db:bb;for(var c=[],d=0;d<a.length;d+=3){var e=a[d],f=d+1<a.length,g=f?a[d+1]:0,h=d+2<a.length,k=h?a[d+2]:0,n=e>>2;e=(e&3)<<4|g>>4;g=(g&15)<<2|k>>6;k&=63;h||(k=64,f||(g=64));c.push(b[n],b[e],b[g],b[k])}return c.join("")},jb=function(a){return fb?p.btoa(a):ib(Fa(a),void 0)},lb=function(a){if(gb)return p.atob(a);var b="";kb(a,function(a){b+=String.fromCharCode(a)});
return b},mb=function(a){var b=[];kb(a,function(a){b.push(a)});return b},kb=function(a,b){function c(b){for(;d<a.length;){var c=a.charAt(d++),e=cb[c];if(null!=e)return e;if(!/^[\s\xa0]*$/.test(c))throw Error("b`"+c);}return b}hb();for(var d=0;;){var e=c(-1),f=c(0),g=c(64),h=c(64);if(64===h&&-1===e)break;b(e<<2|f>>4);64!=g&&(b(f<<4&240|g>>2),64!=h&&b(g<<6&192|h))}},hb=function(){if(!bb){bb={};cb={};db={};for(var a=0;65>a;a++)bb[a]="ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/=".charAt(a), cb[bb[a]]=a,db[a]="ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789-_.".charAt(a),62<=a&&(cb["ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789-_.".charAt(a)]=a)}};
var B=function(){},nb="function"==typeof window.Uint8Array,C=function(a,b,c,d){a.a=null;b||(b=[]);a.j=void 0;a.f=-1;a.b=b;a:{if(b=a.b.length){--b;var e=a.b[b];if(!(null===e||"object"!=typeof e||oa(e)||nb&&e instanceof window.Uint8Array)){a.g=b-a.f;a.c=e;break a}}a.g=Number.MAX_VALUE}a.i={};if(c)for(b=0;b<c.length;b++)e=c[b],e<a.g?(e+=a.f,a.b[e]=a.b[e]||ob):(pb(a),a.c[e]=a.c[e]||ob);if(d&&d.length)for(b=0;b<d.length;b++)qb(a,d[b])},ob=[],pb=function(a){var b=a.g+a.f;a.b[b]||(a.c=a.b[b]={})},D=function(a,
b){if(b<a.g){b+=a.f;var c=a.b[b];return c===ob?a.b[b]=[]:c}if(a.c)return c=a.c[b],c===ob?a.c[b]=[]:c},rb=function(a,b){if(b<a.g){b+=a.f;var c=a.b[b];return c===ob?a.b[b]=[]:c}c=a.c[b];return c===ob?a.c[b]=[]:c},E=function(a,b,c){b<a.g?a.b[b+a.f]=c:(pb(a),a.c[b]=c)},qb=function(a,b){for(var c,d,e=0;e<b.length;e++){var f=b[e],g=D(a,f);null!=g&&(c=f,d=g,E(a,f,void 0))}return c?(E(a,c,d),c):0},sb=function(a,b,c){a.a||(a.a={});if(!a.a[c]){var d=D(a,c);d&&(a.a[c]=new b(d))}return a.a[c]},F=function(a,b,
c){a.a||(a.a={});var d=c?tb(c):c;a.a[b]=c;E(a,b,d)},ub=function(a,b,c,d){a.a||(a.a={});var e=d?tb(d):d;a.a[b]=d;(c=qb(a,c))&&c!==b&&void 0!==e&&(a.a&&c in a.a&&(a.a[c]=void 0),E(a,c,void 0));E(a,b,e)},vb=function(a){if(a.a)for(var b in a.a){var c=a.a[b];if(oa(c))for(var d=0;d<c.length;d++)c[d]&&tb(c[d]);else c&&tb(c)}},tb=function(a){vb(a);return a.b};
B.prototype.h=nb?function(){var a=window.Uint8Array.prototype.toJSON;window.Uint8Array.prototype.toJSON=function(){return ib(this)};try{return JSON.stringify(this.b&&tb(this),wb)}finally{window.Uint8Array.prototype.toJSON=a}}:function(){return JSON.stringify(this.b&&tb(this),wb)};var wb=function(a,b){return"number"!=typeof b||!(0,window.isNaN)(b)&&window.Infinity!==b&&-window.Infinity!==b?b:String(b)},xb=function(a,b){return new a(b?JSON.parse(b):null)};B.prototype.toString=function(){vb(this);return this.b.toString()};
var G=function(a){C(this,a,null,null)};x(G,B);var zb=function(a){C(this,a,null,yb)};x(zb,B);var Ab=function(a){C(this,a,null,null)};x(Ab,B);var Bb=function(a){C(this,a,null,null)};x(Bb,B);var Cb=function(a){C(this,a,null,null)};x(Cb,B);var Db=function(a){C(this,a,null,null)};x(Db,B);var Eb=function(a){C(this,a,null,null)};x(Eb,B);var Fb=function(a){C(this,a,null,null)};x(Fb,B);var Gb=function(a){C(this,a,null,null)};x(Gb,B); var yb=[[1,2,3,4,5,6,7,8,13,14,9,10,11]],Hb=function(a){var b=sa();E(a,1,b)};
var H=function(a){C(this,a,null,Ib)};x(H,B);var Ib=[[1,2,3,4]],Jb=function(a,b){ub(a,2,Ib[0],b)};var I=function(a,b){this.b=a===Kb&&b||"";this.f=Lb};I.prototype.c=!0;I.prototype.a=function(){return this.b};I.prototype.toString=function(){return"Const{"+this.b+"}"};var Mb=function(a){return a instanceof I&&a.constructor===I&&a.f===Lb?a.b:"type_error:Const"},Lb={},Kb={};
var Ob=function(){this.b="";this.f=Nb};Ob.prototype.c=!0;Ob.prototype.a=function(){return this.b};
var Tb=function(a,b){a=Pb(a);a=Qb.exec(a);var c=a[3]||"";return Rb(a[1]+Sb("?",a[2]||"",b)+Sb("#",c,void 0))},Pb=function(a){if(a instanceof Ob&&a.constructor===Ob&&a.f===Nb)return a.b;na(a);return"type_error:TrustedResourceUrl"},Qb=/^([^?#]*)(\?[^#]*)?(#[\s\S]*)?/,Nb={},Rb=function(a){var b=new Ob;b.b=a;return b},Sb=function(a,b,c){if(null==c)return b;if(t(c))return a+(0,window.encodeURIComponent)(c);for(var d in c){var e=c[d];e=oa(e)?e:[e];for(var f=0;f<e.length;f++){var g=e[f];null!=g&&(b+=(b? "&":a)+(0,window.encodeURIComponent)(d)+"="+(0,window.encodeURIComponent)(String(g)))}}return b};
var J=function(){this.b="";this.f=Ub};J.prototype.c=!0;J.prototype.a=function(){return this.b};var Vb=function(a){if(a instanceof J&&a.constructor===J&&a.f===Ub)return a.b;na(a);return"type_error:SafeUrl"},Wb=/^(?:(?:https?|mailto|ftp):|[^:/?#]*(?:[/?#]|$))/i,Ub={},Xb=function(a){var b=new J;b.b=a;return b};Xb("about:blank");
var Yb=function(){this.h=this.h;this.j=this.j};Yb.prototype.h=!1;Yb.prototype.g=function(){if(this.j)for(;this.j.length;)this.j.shift()()};var Zb=function(a,b){this.type=a;this.a=this.target=b;this.W=!0};var $b="closure_listenable_"+(1E6*Math.random()|0),ac=0;var bc=function(a,b,c,d,e){this.listener=a;this.a=null;this.src=b;this.type=c;this.capture=!!d;this.H=e;this.key=++ac;this.C=this.G=!1},cc=function(a){a.C=!0;a.listener=null;a.a=null;a.src=null;a.H=null};var dc=function(a){this.src=a;this.a={};this.b=0};dc.prototype.add=function(a,b,c,d,e){var f=a.toString();a=this.a[f];a||(a=this.a[f]=[],this.b++);var g=ec(a,b,d,e);-1<g?(b=a[g],c||(b.G=!1)):(b=new bc(b,this.src,f,!!d,e),b.G=c,a.push(b));return b};var fc=function(a,b){var c=b.type;c in a.a&&ya(a.a[c],b)&&(cc(b),0==a.a[c].length&&(delete a.a[c],a.b--))},ec=function(a,b,c,d){for(var e=0;e<a.length;++e){var f=a[e];if(!f.C&&f.listener==b&&f.capture==!!c&&f.H==d)return e}return-1};
var gc="closure_lm_"+(1E6*Math.random()|0),hc={},ic=0,jc=function(a,b,c,d,e){if(oa(b))for(var f=0;f<b.length;f++)jc(a,b[f],c,d,e);else(d=pa(d)?!!d.capture:!!d,c=kc(c),a&&a[$b])?(a=a.c,b=String(b).toString(),b in a.a&&(f=a.a[b],c=ec(f,c,d,e),-1<c&&(cc(f[c]),Array.prototype.splice.call(f,c,1),0==f.length&&(delete a.a[b],a.b--)))):a&&(a=lc(a))&&(b=a.a[b.toString()],a=-1,b&&(a=ec(b,c,d,e)),(c=-1<a?b[a]:null)&&"number"!=typeof c&&c&&!c.C&&((e=c.src)&&e[$b]?fc(e.c,c):(d=c.type,b=c.a,e.removeEventListener?
e.removeEventListener(d,b,c.capture):e.detachEvent?e.detachEvent(d in hc?hc[d]:hc[d]="on"+d,b):e.addListener&&e.removeListener&&e.removeListener(b),ic--,(d=lc(e))?(fc(d,c),0==d.b&&(d.src=null,e[gc]=null)):cc(c))))},lc=function(a){a=a[gc];return a instanceof dc?a:null},mc="__closure_events_fn_"+(1E9*Math.random()>>>0),kc=function(a){if(v(a))return a;a[mc]||(a[mc]=function(b){return a.handleEvent(b)});return a[mc]};
var K=function(){Yb.call(this);this.c=new dc(this);this.S=this;this.J=null};x(K,Yb);K.prototype[$b]=!0;K.prototype.removeEventListener=function(a,b,c,d){jc(this,a,b,c,d)};
var L=function(a,b){var c,d=a.J;if(d)for(c=[];d;d=d.J)c.push(d);a=a.S;d=b.type||b;if(t(b))b=new Zb(b,a);else if(b instanceof Zb)b.target=b.target||a;else{var e=b;b=new Zb(d,a);Ma(b,e)}e=!0;if(c)for(var f=c.length-1;0<=f;f--){var g=b.a=c[f];e=nc(g,d,!0,b)&&e}g=b.a=a;e=nc(g,d,!0,b)&&e;e=nc(g,d,!1,b)&&e;if(c)for(f=0;f<c.length;f++)g=b.a=c[f],e=nc(g,d,!1,b)&&e};
K.prototype.g=function(){K.R.g.call(this);if(this.c){var a=this.c,b=0,c;for(c in a.a){for(var d=a.a[c],e=0;e<d.length;e++)++b,cc(d[e]);delete a.a[c];a.b--}}this.J=null};var nc=function(a,b,c,d){b=a.c.a[String(b)];if(!b)return!0;b=b.concat();for(var e=!0,f=0;f<b.length;++f){var g=b[f];if(g&&!g.C&&g.capture==c){var h=g.listener,k=g.H||g.src;g.G&&fc(a.c,g);e=!1!==h.call(k,d)&&e}}return e&&0!=d.W};
var oc=function(){};oc.prototype.a=null;var qc=function(a){var b;(b=a.a)||(b={},pc(a)&&(b[0]=!0,b[1]=!0),b=a.a=b);return b};var rc,sc=function(){};x(sc,oc);var tc=function(a){return(a=pc(a))?new window.ActiveXObject(a):new window.XMLHttpRequest},pc=function(a){if(!a.b&&"undefined"==typeof window.XMLHttpRequest&&"undefined"!=typeof window.ActiveXObject){for(var b=["MSXML2.XMLHTTP.6.0","MSXML2.XMLHTTP.3.0","MSXML2.XMLHTTP","Microsoft.XMLHTTP"],c=0;c<b.length;c++){var d=b[c];try{return new window.ActiveXObject(d),a.b=d}catch(e){}}throw Error("c");}return a.b};rc=new sc;
var M=function(a,b){this.b={};this.a=[];this.c=0;var c=arguments.length;if(1<c){if(c%2)throw Error("d");for(var d=0;d<c;d+=2)this.set(arguments[d],arguments[d+1])}else if(a)if(a instanceof M)for(c=a.u(),d=0;d<c.length;d++)this.set(c[d],a.get(c[d]));else for(d in a)this.set(d,a[d])};M.prototype.o=function(){uc(this);for(var a=[],b=0;b<this.a.length;b++)a.push(this.b[this.a[b]]);return a};M.prototype.u=function(){uc(this);return this.a.concat()};
var uc=function(a){if(a.c!=a.a.length){for(var b=0,c=0;b<a.a.length;){var d=a.a[b];N(a.b,d)&&(a.a[c++]=d);b++}a.a.length=c}if(a.c!=a.a.length){var e={};for(c=b=0;b<a.a.length;)d=a.a[b],N(e,d)||(a.a[c++]=d,e[d]=1),b++;a.a.length=c}};M.prototype.get=function(a,b){return N(this.b,a)?this.b[a]:b};M.prototype.set=function(a,b){N(this.b,a)||(this.c++,this.a.push(a));this.b[a]=b};M.prototype.forEach=function(a,b){for(var c=this.u(),d=0;d<c.length;d++){var e=c[d],f=this.get(e);a.call(b,f,e,this)}}; var N=function(a,b){return Object.prototype.hasOwnProperty.call(a,b)};
var vc=function(a){if(a.o&&"function"==typeof a.o)return a.o();if(t(a))return a.split("");if(u(a)){for(var b=[],c=a.length,d=0;d<c;d++)b.push(a[d]);return b}b=[];c=0;for(d in a)b[c++]=a[d];return b},wc=function(a,b){if(a.forEach&&"function"==typeof a.forEach)a.forEach(b,void 0);else if(u(a)||t(a))ua(a,b,void 0);else{if(a.u&&"function"==typeof a.u)var c=a.u();else if(a.o&&"function"==typeof a.o)c=void 0;else if(u(a)||t(a)){c=[];for(var d=a.length,e=0;e<d;e++)c.push(e)}else for(e in c=[],d=0,a)c[d++]= e;d=vc(a);e=d.length;for(var f=0;f<e;f++)b.call(void 0,d[f],c&&c[f],a)}};
var xc=function(a,b){this.c=a;this.f=b;this.b=0;this.a=null};xc.prototype.get=function(){if(0<this.b){this.b--;var a=this.a;this.a=a.next;a.next=null}else a=this.c();return a};var yc=function(a,b){a.f(b);100>a.b&&(a.b++,b.next=a.a,a.a=b)};var zc=function(a){p.setTimeout(function(){throw a;},0)},Ac,Bc=function(){var a=p.MessageChannel;"undefined"===typeof a&&"undefined"!==typeof window&&window.postMessage&&window.addEventListener&&!A("Presto")&&(a=function(){var a=window.document.createElement("IFRAME");a.style.display="none";a.src="";window.document.documentElement.appendChild(a);var b=a.contentWindow;a=b.document;a.open();a.write("");a.close();var c="callImmediate"+Math.random(),d="file:"==b.location.protocol?"*":b.location.protocol+
"//"+b.location.host;a=w(function(a){if(("*"==d||a.origin==d)&&a.data==c)this.port1.onmessage()},this);b.addEventListener("message",a,!1);this.port1={};this.port2={postMessage:function(){b.postMessage(c,d)}}});if("undefined"!==typeof a&&!A("Trident")&&!A("MSIE")){var b=new a,c={},d=c;b.port1.onmessage=function(){if(q(c.next)){c=c.next;var a=c.O;c.O=null;a()}};return function(a){d.next={O:a};d=d.next;b.port2.postMessage(0)}}return"undefined"!==typeof window.document&&"onreadystatechange"in window.document.createElement("SCRIPT")? function(a){var b=window.document.createElement("SCRIPT");b.onreadystatechange=function(){b.onreadystatechange=null;b.parentNode.removeChild(b);b=null;a();a=null};window.document.documentElement.appendChild(b)}:function(a){p.setTimeout(a,0)}};
var Cc=function(){this.b=this.a=null},Ec=new xc(function(){return new Dc},function(a){a.reset()});Cc.prototype.add=function(a,b){var c=Ec.get();c.set(a,b);this.b?this.b.next=c:this.a=c;this.b=c};var Gc=function(){var a=Fc,b=null;a.a&&(b=a.a,a.a=a.a.next,a.a||(a.b=null),b.next=null);return b},Dc=function(){this.next=this.b=this.a=null};Dc.prototype.set=function(a,b){this.a=a;this.b=b;this.next=null};Dc.prototype.reset=function(){this.next=this.b=this.a=null};
var Kc=function(a,b){Hc||Ic();Jc||(Hc(),Jc=!0);Fc.add(a,b)},Hc,Ic=function(){if(p.Promise&&p.Promise.resolve){var a=p.Promise.resolve(void 0);Hc=function(){a.then(Lc)}}else Hc=function(){var a=Lc;!v(p.setImmediate)||p.Window&&p.Window.prototype&&!A("Edge")&&p.Window.prototype.setImmediate==p.setImmediate?(Ac||(Ac=Bc()),Ac(a)):p.setImmediate(a)}},Jc=!1,Fc=new Cc,Lc=function(){for(var a;a=Gc();){try{a.a.call(a.b)}catch(b){zc(b)}yc(Ec,a)}Jc=!1};
var Mc=function(a){a.prototype.then=a.prototype.then;a.prototype.$goog_Thenable=!0},Nc=function(a){if(!a)return!1;try{return!!a.$goog_Thenable}catch(b){return!1}};var P=function(a,b){this.a=0;this.i=void 0;this.f=this.b=this.c=null;this.g=this.h=!1;if(a!=ma)try{var c=this;a.call(b,function(a){Oc(c,2,a)},function(a){Oc(c,3,a)})}catch(d){Oc(this,3,d)}},Pc=function(){this.next=this.c=this.b=this.f=this.a=null;this.g=!1};Pc.prototype.reset=function(){this.c=this.b=this.f=this.a=null;this.g=!1};var Qc=new xc(function(){return new Pc},function(a){a.reset()}),Rc=function(a,b,c){var d=Qc.get();d.f=a;d.b=b;d.c=c;return d};
P.prototype.then=function(a,b,c){return Sc(this,v(a)?a:null,v(b)?b:null,c)};Mc(P);P.prototype.cancel=function(a){0==this.a&&Kc(function(){var b=new Tc(a);Uc(this,b)},this)};
var Uc=function(a,b){if(0==a.a)if(a.c){var c=a.c;if(c.b){for(var d=0,e=null,f=null,g=c.b;g&&(g.g||(d++,g.a==a&&(e=g),!(e&&1<d)));g=g.next)e||(f=g);e&&(0==c.a&&1==d?Uc(c,b):(f?(d=f,d.next==c.f&&(c.f=d),d.next=d.next.next):Vc(c),Wc(c,e,3,b)))}a.c=null}else Oc(a,3,b)},Yc=function(a,b){a.b||2!=a.a&&3!=a.a||Xc(a);a.f?a.f.next=b:a.b=b;a.f=b},Sc=function(a,b,c,d){var e=Rc(null,null,null);e.a=new P(function(a,g){e.f=b?function(c){try{var e=b.call(d,c);a(e)}catch(n){g(n)}}:a;e.b=c?function(b){try{var e=c.call(d,
b);!q(e)&&b instanceof Tc?g(b):a(e)}catch(n){g(n)}}:g});e.a.c=a;Yc(a,e);return e.a};P.prototype.m=function(a){this.a=0;Oc(this,2,a)};P.prototype.s=function(a){this.a=0;Oc(this,3,a)};
var Oc=function(a,b,c){if(0==a.a){a===c&&(b=3,c=new TypeError("e"));a.a=1;a:{var d=c,e=a.m,f=a.s;if(d instanceof P){Yc(d,Rc(e||ma,f||null,a));var g=!0}else if(Nc(d))d.then(e,f,a),g=!0;else{if(pa(d))try{var h=d.then;if(v(h)){Zc(d,h,e,f,a);g=!0;break a}}catch(k){f.call(a,k);g=!0;break a}g=!1}}g||(a.i=c,a.a=b,a.c=null,Xc(a),3!=b||c instanceof Tc||$c(a,c))}},Zc=function(a,b,c,d,e){var f=!1,g=function(a){f||(f=!0,c.call(e,a))},h=function(a){f||(f=!0,d.call(e,a))};try{b.call(a,g,h)}catch(k){h(k)}},Xc=function(a){a.h||
(a.h=!0,Kc(a.j,a))},Vc=function(a){var b=null;a.b&&(b=a.b,a.b=b.next,b.next=null);a.b||(a.f=null);return b};P.prototype.j=function(){for(var a;a=Vc(this);)Wc(this,a,this.a,this.i);this.h=!1};
var Wc=function(a,b,c,d){if(3==c&&b.b&&!b.g)for(;a&&a.g;a=a.c)a.g=!1;if(b.a)b.a.c=null,ad(b,c,d);else try{b.g?b.f.call(b.c):ad(b,c,d)}catch(e){bd.call(null,e)}yc(Qc,b)},ad=function(a,b,c){2==b?a.f.call(a.c,c):a.b&&a.b.call(a.c,c)},$c=function(a,b){a.g=!0;Kc(function(){a.g&&bd.call(null,b)})},bd=zc,Tc=function(a){z.call(this,a)};x(Tc,z);Tc.prototype.name="cancel";
var cd=function(a,b,c){if(v(a))c&&(a=w(a,c));else if(a&&"function"==typeof a.handleEvent)a=w(a.handleEvent,a);else throw Error("f");return 2147483647<Number(b)?-1:p.setTimeout(a,b||0)};var dd=/^(?:([^:/?#.]+):)?(?:\/\/(?:([^/?#]*)@)?([^/#?]*?)(?::([0-9]+))?(?=[/#?]|$))?([^?#]+)?(?:\?([^#]*))?(?:#([\s\S]*))?$/,ed=function(a,b){if(a){a=a.split("&");for(var c=0;c<a.length;c++){var d=a[c].indexOf("="),e=null;if(0<=d){var f=a[c].substring(0,d);e=a[c].substring(d+1)}else f=a[c];b(f,e?(0,window.decodeURIComponent)(e.replace(/\+/g," ")):"")}}};
var Q=function(a){K.call(this);this.headers=new M;this.w=a||null;this.b=!1;this.s=this.a=null;this.I="";this.f=this.B=this.i=this.A=!1;this.D=0;this.m=null;this.L="";this.F=this.N=!1};x(Q,K);var fd=/^https?$/i,gd=["POST","PUT"],hd=[];Q.prototype.T=function(){this.h||(this.h=!0,this.g());ya(hd,this)};
var ld=function(a,b,c,d){if(a.a)throw Error("g`"+a.I+"`"+b);a.I=b;a.A=!1;a.b=!0;a.a=a.w?tc(a.w):tc(rc);a.s=a.w?qc(a.w):qc(rc);a.a.onreadystatechange=w(a.K,a);try{a.B=!0,a.a.open("POST",String(b),!0),a.B=!1}catch(f){id(a);return}b=c||"";var e=new M(a.headers);d&&wc(d,function(a,b){e.set(b,a)});d=xa(e.u());c=p.FormData&&b instanceof p.FormData;!(0<=ta(gd,"POST"))||d||c||e.set("Content-Type","application/x-www-form-urlencoded;charset=utf-8");e.forEach(function(a,b){this.a.setRequestHeader(b,a)},a);a.L&&
(a.a.responseType=a.L);"withCredentials"in a.a&&a.a.withCredentials!==a.N&&(a.a.withCredentials=a.N);try{jd(a),0<a.D&&(a.F=kd(a.a),a.F?(a.a.timeout=a.D,a.a.ontimeout=w(a.M,a)):a.m=cd(a.M,a.D,a)),a.i=!0,a.a.send(b),a.i=!1}catch(f){id(a)}},kd=function(a){return Qa&&$a()&&"number"==typeof a.timeout&&q(a.ontimeout)},wa=function(a){return"content-type"==a.toLowerCase()};Q.prototype.M=function(){"undefined"!=typeof ja&&this.a&&(L(this,"timeout"),this.abort(8))};
var id=function(a){a.b=!1;a.a&&(a.f=!0,a.a.abort(),a.f=!1);md(a);nd(a)},md=function(a){a.A||(a.A=!0,L(a,"complete"),L(a,"error"))};Q.prototype.abort=function(){this.a&&this.b&&(this.b=!1,this.f=!0,this.a.abort(),this.f=!1,L(this,"complete"),L(this,"abort"),nd(this))};Q.prototype.g=function(){this.a&&(this.b&&(this.b=!1,this.f=!0,this.a.abort(),this.f=!1),nd(this,!0));Q.R.g.call(this)};Q.prototype.K=function(){this.h||(this.B||this.i||this.f?od(this):this.U())};Q.prototype.U=function(){od(this)};
var od=function(a){if(a.b&&"undefined"!=typeof ja&&(!a.s[1]||4!=(a.a?a.a.readyState:0)||2!=pd(a)))if(a.i&&4==(a.a?a.a.readyState:0))cd(a.K,0,a);else if(L(a,"readystatechange"),4==(a.a?a.a.readyState:0)){a.b=!1;try{var b=pd(a);a:switch(b){case 200:case 201:case 202:case 204:case 206:case 304:case 1223:var c=!0;break a;default:c=!1}var d;if(!(d=c)){var e;if(e=0===b){var f=String(a.I).match(dd)[1]||null;if(!f&&p.self&&p.self.location){var g=p.self.location.protocol;f=g.substr(0,g.length-1)}e=!fd.test(f?
f.toLowerCase():"")}d=e}d?(L(a,"complete"),L(a,"success")):md(a)}finally{nd(a)}}},nd=function(a,b){if(a.a){jd(a);var c=a.a,d=a.s[0]?ma:null;a.a=null;a.s=null;b||L(a,"ready");try{c.onreadystatechange=d}catch(e){}}},jd=function(a){a.a&&a.F&&(a.a.ontimeout=null);a.m&&(p.clearTimeout(a.m),a.m=null)},pd=function(a){try{return 2<(a.a?a.a.readyState:0)?a.a.status:-1}catch(b){return-1}};
var qd=function(a){C(this,a,null,null)};x(qd,B);var rd=function(a){C(this,a,null,null)};x(rd,B);var sd=function(a){var b=new rd;a=Pb(a);E(b,4,a);return b};var td=null,ud=function(a){this.a=a},vd=function(a,b){if(a.a){var c=new window.Map;c.set("Content-Type","text/plain");a=Vb(a.a);b=b.h();var d=new Q;hd.push(d);d.c.add("ready",d.T,!0,void 0,void 0);ld(d,a,b,c)}},wd=function(){return td?td:new ud(null)};
var xd=function(a){C(this,a,null,null)};x(xd,B);var yd=function(){this.b=-1};var zd=function(){this.b=64;this.a=[];this.j=[];this.m=[];this.i=[];this.i[0]=128;for(var a=1;a<this.b;++a)this.i[a]=0;this.h=this.f=0;this.reset()};x(zd,yd);zd.prototype.reset=function(){this.a[0]=1732584193;this.a[1]=4023233417;this.a[2]=2562383102;this.a[3]=271733878;this.a[4]=3285377520;this.h=this.f=0};
var Ad=function(a,b,c){c||(c=0);var d=a.m;if(t(b))for(var e=0;16>e;e++)d[e]=b.charCodeAt(c)<<24|b.charCodeAt(c+1)<<16|b.charCodeAt(c+2)<<8|b.charCodeAt(c+3),c+=4;else for(e=0;16>e;e++)d[e]=b[c]<<24|b[c+1]<<16|b[c+2]<<8|b[c+3],c+=4;for(e=16;80>e;e++){var f=d[e-3]^d[e-8]^d[e-14]^d[e-16];d[e]=(f<<1|f>>>31)&4294967295}b=a.a[0];c=a.a[1];var g=a.a[2],h=a.a[3],k=a.a[4];for(e=0;80>e;e++){if(40>e)if(20>e){f=h^c&(g^h);var n=1518500249}else f=c^g^h,n=1859775393;else 60>e?(f=c&g|h&(c|g),n=2400959708):(f=c^g^
h,n=3395469782);f=(b<<5|b>>>27)+f+k+n+d[e]&4294967295;k=h;h=g;g=(c<<30|c>>>2)&4294967295;c=b;b=f}a.a[0]=a.a[0]+b&4294967295;a.a[1]=a.a[1]+c&4294967295;a.a[2]=a.a[2]+g&4294967295;a.a[3]=a.a[3]+h&4294967295;a.a[4]=a.a[4]+k&4294967295};
zd.prototype.c=function(a,b){if(null!=a){q(b)||(b=a.length);for(var c=b-this.b,d=0,e=this.j,f=this.f;d<b;){if(0==f)for(;d<=c;)Ad(this,a,d),d+=this.b;if(t(a))for(;d<b;){if(e[f]=a.charCodeAt(d),++f,++d,f==this.b){Ad(this,e);f=0;break}}else for(;d<b;)if(e[f]=a[d],++f,++d,f==this.b){Ad(this,e);f=0;break}}this.f=f;this.h+=b}};
zd.prototype.g=function(){var a=[],b=8*this.h;56>this.f?this.c(this.i,56-this.f):this.c(this.i,this.b-(this.f-56));for(var c=this.b-1;56<=c;c--)this.j[c]=b&255,b/=256;Ad(this,this.j);for(c=b=0;5>c;c++)for(var d=24;0<=d;d-=8)a[b]=this.a[c]>>d&255,++b;return a};
/*
 Portions of this code are from MochiKit, received by
 The Closure Authors under the MIT license. All other code is Copyright
 2005-2009 The Closure Authors. All Rights Reserved.
*/
var Bd=function(a,b){this.g=[];this.A=a;this.w=b||null;this.f=this.a=!1;this.b=void 0;this.m=this.B=this.i=!1;this.h=0;this.c=null;this.j=0};Bd.prototype.cancel=function(a){if(this.a)this.b instanceof Bd&&this.b.cancel();else{if(this.c){var b=this.c;delete this.c;a?b.cancel(a):(b.j--,0>=b.j&&b.cancel())}this.A?this.A.call(this.w,this):this.m=!0;if(!this.a){a=new Cd(this);if(this.a){if(!this.m)throw new Dd(this);this.m=!1}this.a=!0;this.b=a;this.f=!0;Ed(this)}}};
Bd.prototype.s=function(a,b){this.i=!1;this.a=!0;this.b=b;this.f=!a;Ed(this)};var Fd=function(a,b,c){a.g.push([b,c,void 0]);a.a&&Ed(a)};Bd.prototype.then=function(a,b,c){var d,e,f=new P(function(a,b){d=a;e=b});Fd(this,d,function(a){a instanceof Cd?f.cancel():e(a)});return f.then(a,b,c)};Mc(Bd);
var Gd=function(a){return va(a.g,function(a){return v(a[1])})},Ed=function(a){if(a.h&&a.a&&Gd(a)){var b=a.h,c=Hd[b];c&&(p.clearTimeout(c.a),delete Hd[b]);a.h=0}a.c&&(a.c.j--,delete a.c);b=a.b;for(var d=c=!1;a.g.length&&!a.i;){var e=a.g.shift(),f=e[0],g=e[1];e=e[2];if(f=a.f?g:f)try{var h=f.call(e||a.w,b);q(h)&&(a.f=a.f&&(h==b||h instanceof Error),a.b=b=h);if(Nc(b)||"function"===typeof p.Promise&&b instanceof p.Promise)d=!0,a.i=!0}catch(k){b=k,a.f=!0,Gd(a)||(c=!0)}}a.b=b;d&&(h=w(a.s,a,!0),d=w(a.s,a,
!1),b instanceof Bd?(Fd(b,h,d),b.B=!0):b.then(h,d));c&&(b=new Id(b),Hd[b.a]=b,a.h=b.a)},Dd=function(){z.call(this)};x(Dd,z);Dd.prototype.message="Deferred has already fired";Dd.prototype.name="AlreadyCalledError";var Cd=function(){z.call(this)};x(Cd,z);Cd.prototype.message="Deferred was canceled";Cd.prototype.name="CanceledError";var Id=function(a){this.a=p.setTimeout(w(this.c,this),0);this.b=a};Id.prototype.c=function(){delete Hd[this.a];throw this.b;};var Hd={};
/*

 Copyright 2013 Google Inc. All rights reserved.
 Licensed under the Apache License, Version 2.0 (the "License");
 you may not use this file except in compliance with the License.
 You may obtain a copy of the License at

   http://www.apache.org/licenses/LICENSE-2.0

 Unless required by applicable law or agreed to in writing, software
 distributed under the License is distributed on an "AS IS" BASIS,
 WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 See the License for the specific language governing permissions and
 limitations under the License.
*/
var Jd=function(a){z.call(this,a)};x(Jd,z);var Kd=function(a){z.call(this,a)};x(Kd,Jd);/*

 Copyright 2012 Google Inc. All rights reserved.
 Licensed under the Apache License, Version 2.0 (the "License");
 you may not use this file except in compliance with the License.
 You may obtain a copy of the License at

   http://www.apache.org/licenses/LICENSE-2.0

 Unless required by applicable law or agreed to in writing, software
 distributed under the License is distributed on an "AS IS" BASIS,
 WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 See the License for the specific language governing permissions and
 limitations under the License.
*/
var Ld=function(a){var b=[];ua(a,function(a){b.push(a>>>24&255);b.push(a>>>16&255);b.push(a>>>8&255);b.push(a&255)});return b},Md=function(a){for(var b=1,c=0;c<a.length;c++){var d=a[c];b&=("number"==typeof d&&0<=d&&255>=d&&0==d-Math.floor(d))|0}return 1==b};
var Nd=function(){this.a=null},Od=function(){this.a=null};x(Od,Nd);var Pd=function(){};/*

 Copyright 2014 Google Inc. All rights reserved.
 Licensed under the Apache License, Version 2.0 (the "License");
 you may not use this file except in compliance with the License.
 You may obtain a copy of the License at

   http://www.apache.org/licenses/LICENSE-2.0

 Unless required by applicable law or agreed to in writing, software
 distributed under the License is distributed on an "AS IS" BASIS,
 WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 See the License for the specific language governing permissions and
 limitations under the License.
*/
var Qd=function(a,b){return(-(a>b|0)|0)&(a^b)^b};/*

 Copyright 2011 Google Inc. All rights reserved.
 Licensed under the Apache License, Version 2.0 (the "License");
 you may not use this file except in compliance with the License.
 You may obtain a copy of the License at

   http://www.apache.org/licenses/LICENSE-2.0

 Unless required by applicable law or agreed to in writing, software
 distributed under the License is distributed on an "AS IS" BASIS,
 WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 See the License for the specific language governing permissions and
 limitations under the License.
*/
var R=function(a){this.a=[];if(q(a)){if(!(v(p.Uint8Array)&&a instanceof window.Uint8Array||Md(a)))throw new Kd("Input should be a byte array.");for(var b=a.length,c=Array((b+2)/3|0),d=0;0<=b;b-=3)c[d++]=a[b-1]&255|(a[b-2]&255)<<8|(a[b-3]&255)<<16;this.a=c}this.b=0},S=function(a){var b=new R;b.a.length=a;return b},Rd=function(a){var b=new R;b.a=Aa(a);return b},Sd=function(a){if(0>a||281474976710656<a)throw new Kd("Argument must be a valid integer.");var b=new R;do b.a.push(a&16777215),a=Math.floor(a/
16777216);while(0<a);return b},Td=function(a,b,c){c=-c|0;for(var d=Qd(a.a.length,b.a.length),e=S(d),f=0;f<d;++f)e.a[f]=c&(a.a[f]^b.a[f]);for(f=0;f<d;++f)e.a[f]^=b.a[f];return e},Ud=function(a){for(var b=a.a.length,c=0,d=Array(3*b);0<b;--b)d[c++]=a.a[b-1]>>>16&255,d[c++]=a.a[b-1]>>>8&255,d[c++]=a.a[b-1]&255;for(c=b=a=0;c<d.length;++c)b|=d[c],a+=!b&!d[c];return d.slice(a-(1&!b))};
R.prototype.toString=function(){var a=[],b=this,c=Sd(1E6);do b=Vd(b,c),a.unshift(b.P.a[0]),b=b.V,Wd(b);while(!Xd(b));return a.map(function(a,b){return 0==b||1E6<a?""+a:("000000"+a).slice(-6)}).join("")};var Wd=function(a){for(var b=0,c=0,d=a.a.length-1;0<d;--d)c|=a.a[d],b+=!c&!a.a[d];a.a.length-=b;return a},Yd=function(a){if(0==a.b){for(var b=0,c=0,d=a.a.length-1;0<d;--d)c|=a.a[d],b+=!c&!a.a[d];c=a.a.length-b;b=24*c;c=a.a[c-1];for(c|=!c;0==(c&8388608);)c<<=1,--b;a=a.b=b}else a=a.b;return a};
R.prototype.add=function(a){for(var b=Qd(this.a.length,a.a.length),c=S(b+1),d=0,e=0;e<b;++e)d+=(this.a[e]|0)+(a.a[e]|0),c.a[e]=d&16777215,d>>=24;c.a[b]=d;return c};
var Vd=function(a,b){var c=Yd(b),d=(c+24-1)/24|0;c=24*d-c;b=Zd(b,c);var e=Td(Rd(a.a),Zd(a,c),0==c|0);a=Td($d,S(e.a.length+1),0>=e.a.length+1-d|0);e.a.push(0);for(var f=e.a.length-d-1;0<=f;f--){var g=b.a.length,h=16777216*e.a[g+f]+e.a[g+f-1];var k=b.a[g-1];var n=Math.floor(h/k);k=n-(16777216==n|n*(b.a[g-2]|0)>16777216*(h-n*k)+(e.a[g+f-2]|0));g=0;a.a[f]=k;for(h=0;h<=d;h++)g+=e.a[h+f]-(b.a[h]|0)*k,e.a[h+f]=g&16777215,g=Math.floor(g/16777216);k=g;g=0;a.a[f]+=k;for(h=0;h<=d;h++)g+=e.a[h+f]+(b.a[h]&k),
e.a[h+f]=g&16777215,g>>=24}if(0>c||23<c)throw new Kd("Illegal shift value.");h=e.a.length;b=S(h);f=(1<<c)-1;g=0;for(--h;0<=h;h--)b.a[h]=g+(e.a[h]>>c),g=(e.a[h]&f)<<24-c;c=S(d);for(e=0;e<d;e++)c.a[e]=b.a[e]|0;e=c;Wd(a);return{V:a,P:e}},Xd=function(a){for(var b=$d,c=0,d=0,e=0,f=0,g=Qd(a.a.length,b.a.length)-1;0<=g;--g){var h=a.a[g]|0,k=b.a[g]|0;d|=h<k;c|=h>k&!d;e|=h>k;f|=h<k&!e}return 0==c-f};
R.prototype.and=function(a){for(var b=Qd(this.a.length,a.a.length),c=S(b);0<=b;--b)c.a[b]=(this.a[b]|0)&(a.a[b]|0);return c};R.prototype.or=function(a){for(var b=Qd(this.a.length,a.a.length),c=S(b);0<=b;--b)c.a[b]=this.a[b]|0|a.a[b]|0;return c};R.prototype.xor=function(a){for(var b=Qd(this.a.length,a.a.length),c=S(b);0<=b;--b)c.a[b]=(this.a[b]|0)^(a.a[b]|0);return c}; var Zd=function(a,b){if(0>b||23<b)throw new Kd("Illegal shift value.");for(var c=a.a.length,d=S(c+1),e=(1<<b)-1,f=(1<<24-b)-1,g=0,h=0;h<c;h++)d.a[h]=((a.a[h]&f)<<b)+g,g=a.a[h]>>24-b&e;d.a[c]=g;return Wd(d)},$d=Sd(0);Sd(1);Sd(2);
var be=function(a,b){R.call(this,a);Wd(this);a=1;for(var c=this.a[0],d=1;16777216>d;d<<=1)a*c&d&&(a|=d);this.f=16777216-a;if(q(b))b=new R(b);else{b=this.a.length;a=S(2*b+1);for(c=0;c<2*b;++c)a.a[c]=0;a.a[2*b]=1;b=Vd(a,this).P}this.g=b;this.c=ae(this,this.g)};x(be,R);
be.prototype.pow=function(a,b){a=new R(a);b instanceof R&&(b=Ud(b));var c=T(this,a,this.g);a=Array(16);a[0]=this.c;for(var d=1;16>d;++d)a[d]=T(this,c,a[d-1]);c=S(this.a.length);d=Rd(this.c.a);for(var e=b.length,f=0;f<e;++f)T(this,d,d,c),T(this,c,c,d),T(this,d,d,c),T(this,c,c,d),T(this,d,a[b[f]>>4&15],c),T(this,c,c,d),T(this,d,d,c),T(this,c,c,d),T(this,d,d,c),T(this,c,a[b[f]&15],d);ae(this,d,c);return Ud(c)};
var ae=function(a,b,c){var d=a.a.length;c=c||S(d);for(var e=0;e<d;++e)c.a[e]=b.a[e];for(e=0;e<d;++e){b=a;var f=c,g=f.a[0],h=g*b.f&16777215;g+=h*b.a[0];for(var k=1,n=b.a.length;k<n;++k)g=(g/16777216|0)+f.a[k]+h*b.a[k],f.a[k-1]=g&16777215;f.a[k-1]=g/16777216|0}ce(a,c,d);return c},T=function(a,b,c,d){var e=a.a.length;d=d||S(e);for(var f=0;f<e;++f)d.a[f]=0;for(f=0;f<e;++f){var g=a,h=b.a[f]|0,k=c,n=d,r=h*k.a[0]+n.a[0],y=(r&16777215)*g.f&16777215;r+=y*g.a[0];for(var O=1,nf=g.a.length;O<nf;++O)r=(r/16777216|
0)+h*(k.a[O]|0)+n.a[O]+y*g.a[O],n.a[O-1]=r&16777215;n.a[O-1]=r/16777216|0}ce(a,d,e);return d},ce=function(a,b,c){for(var d=0,e=0;e<c;++e)d+=b.a[e]-a.a[e],b.a[e]=d&16777215,d>>=24;var f=d>>24;for(e=d=0;e<c;++e)d+=b.a[e]+(a.a[e]&f),b.a[e]=d&16777215,d>>=24};
var de=function(a,b,c){this.c=a;this.f=this.b=b;this.a=null;this.modulusLength=0;this.a=new be(a,c);this.modulusLength=Math.ceil(Yd(this.a)/8)};x(de,Pd);var ge=function(a,b){this.b=64;this.h=p.Uint8Array?new window.Uint8Array(this.b):Array(this.b);this.i=this.f=0;this.a=[];this.m=a;this.j=b;this.s=p.Int32Array?new window.Int32Array(64):Array(64);q(ee)||(p.Int32Array?ee=new window.Int32Array(fe):ee=fe);this.reset()},ee;x(ge,yd);var he=za(128,Da(0,63));ge.prototype.reset=function(){this.i=this.f=0;this.a=p.Int32Array?new window.Int32Array(this.j):Aa(this.j)};
var ie=function(a){for(var b=a.h,c=a.s,d=0,e=0;e<b.length;)c[d++]=b[e]<<24|b[e+1]<<16|b[e+2]<<8|b[e+3],e=4*d;for(b=16;64>b;b++){e=c[b-15]|0;d=c[b-2]|0;var f=(c[b-16]|0)+((e>>>7|e<<25)^(e>>>18|e<<14)^e>>>3)|0,g=(c[b-7]|0)+((d>>>17|d<<15)^(d>>>19|d<<13)^d>>>10)|0;c[b]=f+g|0}d=a.a[0]|0;e=a.a[1]|0;var h=a.a[2]|0,k=a.a[3]|0,n=a.a[4]|0,r=a.a[5]|0,y=a.a[6]|0;f=a.a[7]|0;for(b=0;64>b;b++){var O=((d>>>2|d<<30)^(d>>>13|d<<19)^(d>>>22|d<<10))+(d&e^d&h^e&h)|0;g=n&r^~n&y;f=f+((n>>>6|n<<26)^(n>>>11|n<<21)^(n>>>
25|n<<7))|0;g=g+(ee[b]|0)|0;g=f+(g+(c[b]|0)|0)|0;f=y;y=r;r=n;n=k+g|0;k=h;h=e;e=d;d=g+O|0}a.a[0]=a.a[0]+d|0;a.a[1]=a.a[1]+e|0;a.a[2]=a.a[2]+h|0;a.a[3]=a.a[3]+k|0;a.a[4]=a.a[4]+n|0;a.a[5]=a.a[5]+r|0;a.a[6]=a.a[6]+y|0;a.a[7]=a.a[7]+f|0};
ge.prototype.c=function(a,b){q(b)||(b=a.length);var c=0,d=this.f;if(t(a))for(;c<b;)this.h[d++]=a.charCodeAt(c++),d==this.b&&(ie(this),d=0);else if(u(a))for(;c<b;){var e=a[c++];if(!("number"==typeof e&&0<=e&&255>=e&&e==(e|0)))throw Error("h");this.h[d++]=e;d==this.b&&(ie(this),d=0)}else throw Error("i");this.f=d;this.i+=b};
ge.prototype.g=function(){var a=[],b=8*this.i;56>this.f?this.c(he,56-this.f):this.c(he,this.b-(this.f-56));for(var c=63;56<=c;c--)this.h[c]=b&255,b/=256;ie(this);for(c=b=0;c<this.m;c++)for(var d=24;0<=d;d-=8)a[b++]=this.a[c]>>d&255;return a};
var fe=[1116352408,1899447441,3049323471,3921009573,961987163,1508970993,2453635748,2870763221,3624381080,310598401,607225278,1426881987,1925078388,2162078206,2614888103,3248222580,3835390401,4022224774,264347078,604807628,770255983,1249150122,1555081692,1996064986,2554220882,2821834349,2952996808,3210313671,3336571891,3584528711,113926993,338241895,666307205,773529912,1294757372,1396182291,1695183700,1986661051,2177026350,2456956037,2730485921,2820302411,3259730800,3345764771,3516065817,3600352804, 4094571909,275423344,430227734,506948616,659060556,883997877,958139571,1322822218,1537002063,1747873779,1955562222,2024104815,2227730452,2361852424,2428436474,2756734187,3204031479,3329325298];
var ke=function(){ge.call(this,8,je)};x(ke,ge);var je=[1779033703,3144134277,1013904242,2773480762,1359893119,2600822924,528734635,1541459225];var U=function(a,b){this.b=a|0;this.a=b|0},oe=function(a){return 0<a?0x7fffffffffffffff<=a?le:new U(a,a/4294967296):0>a?-9223372036854775808>=a?me:V(new U(-a,-a/4294967296)):ne},W=function(a,b){return new U(a,b)},ne=W(0,0),pe=W(1,0),qe=W(-1,-1),le=W(4294967295,2147483647),me=W(0,2147483648),re=function(a){return 4294967296*a.a+(a.b>>>0)};
U.prototype.toString=function(a){a=a||10;if(2>a||36<a)throw Error("j`"+a);var b=this.a>>21;if(0==b||-1==b&&(0!=this.b||-2097152!=this.a))return b=re(this),10==a?""+b:b.toString(a);b=14-(a>>2);var c=Math.pow(a,b),d=W(c,c/4294967296);c=se(this,d);d=Math.abs(re(this.add(V(te(c,d)))));var e=10==a?""+d:d.toString(a);e.length<b&&(e="0000000000000".substr(e.length-b)+e);d=re(c);return(10==a?d:d.toString(a))+e};
var ue=function(a){return 0==a.b&&0==a.a},ve=function(a,b){return a.b==b.b&&a.a==b.a},we=function(a,b){return a.a==b.a?a.b==b.b?0:a.b>>>0>b.b>>>0?1:-1:a.a>b.a?1:-1},V=function(a){var b=~a.b+1|0;return W(b,~a.a+!b|0)};U.prototype.add=function(a){var b=this.a>>>16,c=this.a&65535,d=this.b>>>16,e=a.a>>>16,f=a.a&65535,g=a.b>>>16;a=(this.b&65535)+(a.b&65535);g=(a>>>16)+(d+g);d=g>>>16;d+=c+f;b=(d>>>16)+(b+e)&65535;return W((g&65535)<<16|a&65535,b<<16|d&65535)};
var te=function(a,b){if(ue(a))return a;if(ue(b))return b;var c=a.a>>>16,d=a.a&65535,e=a.b>>>16;a=a.b&65535;var f=b.a>>>16,g=b.a&65535,h=b.b>>>16;b=b.b&65535;var k=a*b;var n=(k>>>16)+e*b;var r=n>>>16;n=(n&65535)+a*h;r+=n>>>16;r+=d*b;var y=r>>>16;r=(r&65535)+e*h;y+=r>>>16;r=(r&65535)+a*g;y=y+(r>>>16)+(c*b+d*h+e*g+a*f)&65535;return W((n&65535)<<16|k&65535,y<<16|r&65535)},se=function(a,b){if(ue(b))throw Error("k");if(0>a.a){if(ve(a,me)){if(ve(b,pe)||ve(b,qe))return me;if(ve(b,me))return pe;var c=1;if(0==
c)c=a;else{var d=a.a;c=32>c?W(a.b>>>c|d<<32-c,d>>c):W(d>>c-32,0<=d?0:-1)}c=se(c,b);d=1;if(0!=d){var e=c.b;c=32>d?W(e<<d,c.a<<d|e>>>32-d):W(0,e<<d-32)}if(ve(c,ne))return 0>b.a?pe:qe;a=a.add(V(te(b,c)));return c.add(se(a,b))}return 0>b.a?se(V(a),V(b)):V(se(V(a),b))}if(ue(a))return ne;if(0>b.a)return ve(b,me)?ne:V(se(a,V(b)));for(d=ne;0<=we(a,b);){c=Math.max(1,Math.floor(re(a)/re(b)));e=Math.ceil(Math.log(c)/Math.LN2);e=48>=e?1:Math.pow(2,e-48);for(var f=oe(c),g=te(f,b);0>g.a||0<we(g,a);)c-=e,f=oe(c), g=te(f,b);ue(f)&&(f=pe);d=d.add(f);a=a.add(V(g))}return d};U.prototype.and=function(a){return W(this.b&a.b,this.a&a.a)};U.prototype.or=function(a){return W(this.b|a.b,this.a|a.a)};U.prototype.xor=function(a){return W(this.b^a.b,this.a^a.a)};
for(var xe=[1116352408,3609767458,1899447441,602891725,3049323471,3964484399,3921009573,2173295548,961987163,4081628472,1508970993,3053834265,2453635748,2937671579,2870763221,3664609560,3624381080,2734883394,310598401,1164996542,607225278,1323610764,1426881987,3590304994,1925078388,4068182383,2162078206,991336113,2614888103,633803317,3248222580,3479774868,3835390401,2666613458,4022224774,944711139,264347078,2341262773,604807628,2007800933,770255983,1495990901,1249150122,1856431235,1555081692,3175218132,
1996064986,2198950837,2554220882,3999719339,2821834349,766784016,2952996808,2566594879,3210313671,3203337956,3336571891,1034457026,3584528711,2466948901,113926993,3758326383,338241895,168717936,666307205,1188179964,773529912,1546045734,1294757372,1522805485,1396182291,2643833823,1695183700,2343527390,1986661051,1014477480,2177026350,1206759142,2456956037,344077627,2730485921,1290863460,2820302411,3158454273,3259730800,3505952657,3345764771,106217008,3516065817,3606008344,3600352804,1432725776,4094571909,
1467031594,275423344,851169720,430227734,3100823752,506948616,1363258195,659060556,3750685593,883997877,3785050280,958139571,3318307427,1322822218,3812723403,1537002063,2003034995,1747873779,3602036899,1955562222,1575990012,2024104815,1125592928,2227730452,2716904306,2361852424,442776044,2428436474,593698344,2756734187,3733110249,3204031479,2999351573,3329325298,3815920427,3391569614,3928383900,3515267271,566280711,3940187606,3454069534,4118630271,4000239992,116418474,1914138554,174292421,2731055270,
289380356,3203993006,460393269,320620315,685471733,587496836,852142971,1086792851,1017036298,365543100,1126000580,2618297676,1288033470,3409855158,1501505948,4234509866,1607167915,987167468,1816402316,1246189591],ye=[],ze=0;ze<xe.length;ze+=2)ye.push(new U(xe[ze+1],xe[ze]));
var Ae=function(){this.b=-1};x(Ae,yd);Ae.prototype.reset=function(){this.a.reset()};Ae.prototype.g=function(){return this.a.g()};Ae.prototype.c=function(a,b){this.a.c(a,b)};Ae.prototype.hash=function(a){this.reset();this.c(a);return this.g()};var Be=function(){this.b=-1;this.a=new ke;this.b=this.a.b};x(Be,Ae);Be.prototype.f="SHA256";var Ce=function(a){z.call(this,a)};x(Ce,z);var De={MD5:[48,32,48,12,6,8,42,134,72,134,247,13,2,5,5,0,4,16],RIPEMD160:[48,33,48,9,6,5,43,36,3,2,1,5,0,4,20],SHA1:[48,33,48,9,6,5,43,14,3,2,26,5,0,4,20],SHA224:[48,45,48,13,6,9,96,134,72,1,101,3,4,2,4,5,0,4,28],SHA256:[48,49,48,13,6,9,96,134,72,1,101,3,4,2,1,5,0,4,32],SHA384:[48,65,48,13,6,9,96,134,72,1,101,3,4,2,2,5,0,4,48],SHA512:[48,81,48,13,6,9,96,134,72,1,101,3,4,2,3,5,0,4,64]};
var Ee=function(a,b,c,d){de.call(this,a,b,c);this.g=d||new Be};x(Ee,de);var Fe=function(a,b,c,d){this.a=null;this.b=new Ee(a,b,c,d)};x(Fe,Od);var Ge=function(a){this.a=a};var He=function(a,b){this.a=new Ge(new Fe(a,b))};var Ie=function(a,b,c,d,e){this.a="U";this.b=0;a&&(a=a.split(","))&&2==a.length&&(this.a=a[0],this.b=(0,window.parseInt)(a[1],10));if(0>=b||0>=c||0>=d)throw Error("l");this.h=b;this.c=c;this.g=d;this.f=e},Je=function(a){switch(a.a){case "Y":return a.h;case "N":return a.c;case "P":return a.f;default:return a.g}},Ke=function(a,b,c,d,e,f){this.g=new He(mb(a),mb(b));this.f=c;this.a=d;this.c=e;this.b=f};
var Le=function(a){this.a=a||{cookie:""}};Le.prototype.set=function(a,b,c,d,e,f){if(/[;=\s]/.test(a))throw Error("m`"+a);if(/[;\r\n]/.test(b))throw Error("n`"+b);q(c)||(c=-1);e=e?";domain="+e:"";d=d?";path="+d:"";f=f?";secure":"";c=0>c?"":0==c?";expires="+(new Date(1970,1,1)).toUTCString():";expires="+(new Date(sa()+1E3*c)).toUTCString();this.a.cookie=a+"="+b+e+d+c+f};
Le.prototype.get=function(a,b){for(var c=a+"=",d=(this.a.cookie||"").split(";"),e=0,f;e<d.length;e++){f=Ga(d[e]);if(0==f.lastIndexOf(c,0))return f.substr(c.length);if(f==a)return""}return b};var Me=function(a,b,c){a.get("DATA_USE_CONSENT");a.set("DATA_USE_CONSENT","",0,b,c)};Le.prototype.u=function(){return Ne(this).keys};Le.prototype.o=function(){return Ne(this).values}; var Ne=function(a){a=(a.a.cookie||"").split(";");for(var b=[],c=[],d,e,f=0;f<a.length;f++)e=Ga(a[f]),d=e.indexOf("="),-1==d?(b.push(""),c.push(e)):(b.push(e.substring(0,d)),c.push(e.substring(d+1)));return{keys:b,values:c}};
var Oe=function(a,b,c,d,e,f,g,h){this.a=a;this.b=new Ke(b,c,e,f,g,h);this.c=d},Pe=function(a){var b;if(b=(new Le(window.document)).get(a.a,"")){var c=a.b;var d=c.g;a=Fa(a.c);b=mb(b.substr(b.indexOf(":")+1));d=d.a;var e=d.a;if(!e.a){var f=new zd;f.c(Ld([e.b.c.length]));f.c(e.b.c);f.c(Ld([e.b.b.length]));f.c(e.b.b);f=f.g();var g=Array(5);g[0]=0;g[1]=f[0];g[2]=f[1];g[3]=f[2];g[4]=f[3];e.a=g}e=e.a;b:if(f=Ca(b,0,e.length),u(e)&&u(f)&&e.length==f.length){g=e.length;for(var h=0;h<g;h++)if(e[h]!==f[h]){f=
!1;break b}f=!0}else f=!1;if(f){f=e.length+4;e=Ca(b,e.length,f);g=[];for(h=0;h<e.length;h+=4)g.push((e[h+3]|e[h+2]<<8|e[h+1]<<16|e[h]<<24)>>>0);g=g[0];if(f+g>b.length)b=null;else{e=Ca(b,f,f+g);a=Ea(e,Ld([a.length]),a,b[0]);d=d.a.b;b=d.a.pow(Ca(b,f+g),d.f);f=d.g;d=d.modulusLength-1;g=f.hash(a);a=[];if(!q(De[f.f]))throw new Ce("invalid hash for signature");Ba(a,De[f.f]);Ba(a,g);f=a.length;if(d<f+11)throw new Ce("intended encoded message length too short");a=[1].concat(Da(255,d-f-3+1)).concat([0]).concat(a);
if(a.length===b.length&&Md(a)&&Md(b)){d=1;for(f=0;f<a.length;f++)d&=!(a[f]^b[f])|0;b=1==d}else b=!1;b=b?e:null}}else b=null;if(b)if(8192>=b.length)b=String.fromCharCode.apply(null,b);else{a="";for(d=0;d<b.length;d+=8192)a+=String.fromCharCode.apply(null,Ca(b,d,d+8192));b=a}else b=null;c=new Ie(b,c.f,c.a,c.c,c.b)}else c=null;return c?"Y"==c.a&&!(c.b+Je(c)<sa()):!1};
var Qe=function(a,b){a.src=Pb(b);if(null===la){a:{b=p.document;if((b=b.querySelector&&b.querySelector("script[nonce]"))&&(b=b.nonce||b.getAttribute("nonce"))&&ka.test(b))break a;b=null}la=b||""}(b=la)&&a.setAttribute("nonce",b)},Re=function(a){var b=p.location;a instanceof J||a instanceof J||(a="object"==typeof a&&a.c?a.a():String(a),Wb.test(a)||(a="about:invalid#zClosurez"),a=Xb(a));b.href=Vb(a)};
var Se=function(a){this.a=a||p.document||window.document};var Te=function(a,b,c,d,e,f){try{var g=a.a,h=a.a.createElement("SCRIPT");h.async=!0;Qe(h,b);g.head.appendChild(h);h.addEventListener("load",function(){e();d&&g.head.removeChild(h)});h.addEventListener("error",function(){0<c?Te(a,b,c-1,d,e,f):(d&&g.head.removeChild(h),f())})}catch(k){f()}};
var Ue=function(a,b,c){for(var d=[],e=2;e<arguments.length;++e)d[e-2]=arguments[e];e=jb(a+b);e=p[e];if(v(e))e.apply(null,d);else throw Error("o");};var Ve=function(a){C(this,a,null,null)};x(Ve,B);var We=function(a){C(this,a,null,null)};x(We,B);var Xe=function(){return p.googlefc||(p.googlefc={})},Ye=function(a,b){var c=Xe();c.hasOwnProperty(a)||(c[a]=b)};var Ze=function(){this.a=0;this.b=wd()};Ze.prototype.push=function(a){var b=new G;Hb(b);var c=new Db;try{v(a)&&a(),this.a++,E(c,1,!1)}catch(d){window.console&&window.console.error&&window.console.error("Exception in queued FC callback",d),E(c,1,!0)}a=new Cb;F(a,1,c);F(b,5,a);c=new H;Jb(c,b);vd(this.b,c);return this.a};var $e=function(){var a=Xe().callbackQueue;if(!a||oa(a)){var b=new Ze;Xe().callbackQueue=b;if(a&&0<a.length)for(var c=0;c<a.length;c++)b.push(a[c])}};
var af={UNKNOWN:0,CONSENTED_TO_PERSONALIZED_ADS:1,CONSENTED_TO_NON_PERSONALIZED_ADS:2,CONTRIBUTOR:3,NO_CONSENT:4,CONSENT_NOT_REQUIRED:5};Ye("ConsentStatusEnum",af);var cf=function(a){C(this,a,bf,null)};x(cf,B);var bf=[1,2,3,4];var df=function(a,b,c,d){this.a=new Le(a);this.f=b;this.b=c;this.c=d};df.prototype.get=function(a){a=this.a.get(a);return void 0===a?null:a};df.prototype.set=function(a,b){this.a.set(a,b,this.f,this.b,this.c)};var ef=function(a){Me(a.a,a.b,a.c);for(var b=p.location.hostname.split(".");2<b.length;)b.shift(),Me(a.a,a.b,b.join("."))};
var ff=function(){var a=new df(window.document,0,"","");try{var b=a.get("DATA_USE_CONSENT")}catch(c){}if(!b)return null;try{return xb(cf,b)}catch(c){return null}};var gf=function(a,b){this.a=a;this.c=b;this.b=wd()},hf=function(a){var b=new G;Hb(b);var c=new Eb,d=new Cb;F(d,2,c);F(b,5,d);c=new H;Jb(c,b);vd(a.b,c);if(null!=a.c&&!a.c)return af.CONSENT_NOT_REQUIRED;if(Pe(new Oe(D(a.a,1),D(a.a,5),D(a.a,4),D(a.a,6),D(a.a,8),D(a.a,9),D(a.a,10),D(a.a,11))))return af.CONTRIBUTOR;a=ff();return a?(b=rb(a,2))&&b.length?af.CONSENTED_TO_NON_PERSONALIZED_ADS:(a=rb(a,1))&&a.length?af.CONSENTED_TO_PERSONALIZED_ADS:af.UNKNOWN:af.NO_CONSENT};
var jf=Qa?Rb(Mb(new I(Kb,'javascript:""'))):Rb(Mb(new I(Kb,"about:blank"))),kf=function(){this.a=new Se(p.top.document)},mf=function(a,b){if(!lf(a,b)){var c=a.a.a.createElement("IFRAME");c.name=b;c.src=Pb(jf);c.style.display="none";c.style.width="0px";c.style.height="0px";c.style.border="none";c.style.zIndex="-1000";c.style.left="-1000px";c.style.top="-1000px";var d=function(){a.a.a.body?a.a.a.body.appendChild(c):p.setTimeout(d,5)};d()}},lf=function(a,b){return va(a.a.a.getElementsByTagName("IFRAME"), function(a){return a.name===b})};
var of=function(a,b){this.f=this.j=this.c="";this.i=null;this.g=this.h="";this.a=!1;if(a instanceof of){this.a=q(b)?b:a.a;pf(this,a.c);this.j=a.j;this.f=a.f;qf(this,a.i);this.h=a.h;b=a.b;var c=new X;c.c=b.c;b.a&&(c.a=new M(b.a),c.b=b.b);rf(this,c);this.g=a.g}else a&&(c=String(a).match(dd))?(this.a=!!b,pf(this,c[1]||"",!0),this.j=sf(c[2]||""),this.f=sf(c[3]||"",!0),qf(this,c[4]),this.h=sf(c[5]||"",!0),rf(this,c[6]||"",!0),this.g=sf(c[7]||"")):(this.a=!!b,this.b=new X(null,this.a))};
of.prototype.toString=function(){var a=[],b=this.c;b&&a.push(tf(b,uf,!0),":");var c=this.f;if(c||"file"==b)a.push("//"),(b=this.j)&&a.push(tf(b,uf,!0),"@"),a.push((0,window.encodeURIComponent)(String(c)).replace(/%25([0-9a-fA-F]{2})/g,"%$1")),c=this.i,null!=c&&a.push(":",String(c));if(c=this.h)this.f&&"/"!=c.charAt(0)&&a.push("/"),a.push(tf(c,"/"==c.charAt(0)?vf:wf,!0));(c=this.b.toString())&&a.push("?",c);(c=this.g)&&a.push("#",tf(c,xf));return a.join("")};
var pf=function(a,b,c){a.c=c?sf(b,!0):b;a.c&&(a.c=a.c.replace(/:$/,""))},qf=function(a,b){if(b){b=Number(b);if((0,window.isNaN)(b)||0>b)throw Error("p`"+b);a.i=b}else a.i=null},rf=function(a,b,c){b instanceof X?(a.b=b,yf(a.b,a.a)):(c||(b=tf(b,zf)),a.b=new X(b,a.a))},sf=function(a,b){return a?b?(0,window.decodeURI)(a.replace(/%25/g,"%2525")):(0,window.decodeURIComponent)(a):""},tf=function(a,b,c){return t(a)?(a=(0,window.encodeURI)(a).replace(b,Af),c&&(a=a.replace(/%25([0-9a-fA-F]{2})/g,"%$1")),a):
null},Af=function(a){a=a.charCodeAt(0);return"%"+(a>>4&15).toString(16)+(a&15).toString(16)},uf=/[#\/\?@]/g,wf=/[#\?:]/g,vf=/[#\?]/g,zf=/[#\?@]/g,xf=/#/g,X=function(a,b){this.b=this.a=null;this.c=a||null;this.f=!!b},Y=function(a){a.a||(a.a=new M,a.b=0,a.c&&ed(a.c,function(b,c){a.add((0,window.decodeURIComponent)(b.replace(/\+/g," ")),c)}))};X.prototype.add=function(a,b){Y(this);this.c=null;a=Bf(this,a);var c=this.a.get(a);c||this.a.set(a,c=[]);c.push(b);this.b+=1;return this};
var Cf=function(a,b){Y(a);b=Bf(a,b);N(a.a.b,b)&&(a.c=null,a.b-=a.a.get(b).length,a=a.a,N(a.b,b)&&(delete a.b[b],a.c--,a.a.length>2*a.c&&uc(a)))},Df=function(a,b){Y(a);b=Bf(a,b);return N(a.a.b,b)};X.prototype.forEach=function(a,b){Y(this);this.a.forEach(function(c,d){ua(c,function(c){a.call(b,c,d,this)},this)},this)};X.prototype.u=function(){Y(this);for(var a=this.a.o(),b=this.a.u(),c=[],d=0;d<b.length;d++)for(var e=a[d],f=0;f<e.length;f++)c.push(b[d]);return c};
X.prototype.o=function(a){Y(this);var b=[];if(t(a))Df(this,a)&&(b=za(b,this.a.get(Bf(this,a))));else{a=this.a.o();for(var c=0;c<a.length;c++)b=za(b,a[c])}return b};X.prototype.set=function(a,b){Y(this);this.c=null;a=Bf(this,a);Df(this,a)&&(this.b-=this.a.get(a).length);this.a.set(a,[b]);this.b+=1;return this};X.prototype.get=function(a,b){if(!a)return b;a=this.o(a);return 0<a.length?String(a[0]):b};
X.prototype.toString=function(){if(this.c)return this.c;if(!this.a)return"";for(var a=[],b=this.a.u(),c=0;c<b.length;c++){var d=b[c],e=(0,window.encodeURIComponent)(String(d));d=this.o(d);for(var f=0;f<d.length;f++){var g=e;""!==d[f]&&(g+="="+(0,window.encodeURIComponent)(String(d[f])));a.push(g)}}return this.c=a.join("&")};
var Bf=function(a,b){b=String(b);a.f&&(b=b.toLowerCase());return b},yf=function(a,b){b&&!a.f&&(Y(a),a.c=null,a.a.forEach(function(a,b){var c=b.toLowerCase();b!=c&&(Cf(this,b),Cf(this,c),0<a.length&&(this.c=null,this.a.set(Bf(this,c),Aa(a)),this.b+=a.length))},a));a.f=b};
var Ef=function(a){a=a.location.href;a=(a instanceof of?new of(a):new of(a,void 0)).b.get("fcconsent");return"alwaysshow"===a?a:null};var Ff=function(a,b){this.a=new df(a,33696E3,"/",b);this.b=new kf},Gf=function(a,b,c){b.forEach(function(b){mf(a.b,"googlefcPA-"+b)});(b.length||c.length)&&mf(a.b,"googlefcNPA")};var Hf=function(a,b,c){this.a=a;this.b=b;this.c=c;this.g=new Ff(window.document,p.location.hostname);this.f=wd()},If=function(a){ef(a.g.a);var b=new G;Hb(b);var c=new Gb,d=new Cb;F(d,4,c);F(b,5,d);c=new H;Jb(c,b);vd(a.f,c);Pe(new Oe(D(a.a,1),D(a.a,5),D(a.a,4),D(a.a,6),D(a.a,8),D(a.a,9),D(a.a,10),D(a.a,11)))?Re(a.c):(b=a.b,(c=Ef(p))&&(b=Tb(a.b,{fcconsent:c})),Te(new Se(window.document),b,3,!1,function(){},function(){}))};
var Jf=function(a,b,c){this.a=a;this.c=b;this.b=c};Jf.prototype.load=function(a){var b=new gf(this.a,a);Ye("getConsentStatus",function(){return hf(b)});Ye("getConsentedProviderIds",function(){var a=ff(),c=new G;Hb(c);var f=new Fb,g=new Cb;F(g,3,f);F(c,5,g);f=new H;Jb(f,c);vd(b.b,f);return a?rb(a,1):[]});var c=new Hf(this.a,this.c,this.b);Ye("showRevocationMessage",function(){return If(c)});$e()};
/*

Math.uuid.js (v1.4)
http://www.broofa.com
mailto:robert@broofa.com
Copyright (c) 2010 Robert Kieffer
Dual licensed under the MIT and GPL licenses.
*/
var Kf="0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz".split("");var Lf=function(a,b){this.b=a;this.a=sb(b,Ve,1);this.f=new Ff(this.b.document,this.b.location.hostname);this.c=Ef(a);a=Array(36);for(var c=0,d,e=0;36>e;e++)8==e||13==e||18==e||23==e?a[e]="-":14==e?a[e]="4":(2>=c&&(c=33554432+16777216*Math.random()|0),d=c&15,c>>=4,a[e]=Kf[19==e?d&3|8:d]);this.g=a.join("");this.h=D(b,3);this.i=D(b,4)},Nf=function(a,b){if(a.c){var c={};c.fcconsent=a.c;b=Tb(b,c)}if(a.h){var d=a.i,e=sa();Ue(d,"internal_api_load_with_sb",sd(b).h(),function(){var a=jb(d+"messaging_js");
(a=p[a])?(a=lb(a),a=3E5>Math.abs(e-(0,window.parseInt)(a,10))):a=!1;a||Ue(d,"internal_api_sb")},function(){Mf()})}else Te(new Se(a.b.document),b,0,!1,function(){},function(){Mf()})},Mf=function(){var a=wd(),b=new G;Hb(b);var c=new Ab,d=new zb;ub(d,14,yb[0],c);F(b,3,d);c=new H;Jb(c,b);vd(a,c)};
var Of=function(a,b){b=xb(We,lb(b));a=new Lf(a,b);if(b=!a.b.frameElement)null==D(a.a,1)||null==D(a.a,2)?b=!1:(b=sb(a.a,xd,2),b=null!=D(b,1)&&null!=D(b,5)&&null!=D(b,4)&&null!=D(b,6)&&null!=D(b,3)&&null!=D(b,2));if(b){b=sb(a.a,xd,2);var c=new Oe(D(b,1),D(b,5),D(b,4),D(b,6),D(b,8),D(b,9),D(b,10),D(b,11)),d={};d.pvid=a.g;var e=sb(a.a,rd,1);e=Rb(D(e,4)||"");d=Tb(e,d);e=sb(a.a,rd,4);if(!td){var f={};f.pvid=a.g;td=new ud(e?Xb(Pb(Tb(Rb(D(e,4)||""),f))):null)}e=td;if(Pe(c)){ef(a.f.a);var g=sb(a.a,qd,3);g=
Xb(D(g,3)||"");(new Jf(b,d,g)).load(null);g=new G;Hb(g);a=new Bb;b=new zb;ub(b,11,yb[0],a);F(g,3,b);a=new H;Jb(a,g);vd(e,a)}else{b=a.f;if(e=b.a.get("DATA_USE_CONSENT"))try{g=xb(cf,e)}catch(h){g=null}else g=null;g&&(D(g,7)?mf(b.b,"googlefcInactive"):6048E5<sa()-D(g,5)||Gf(b,rb(g,3),rb(g,4)));Nf(a,d)}}},Pf=["__TqF050x7LrBv__"],Z=p;Pf[0]in Z||"undefined"==typeof Z.execScript||Z.execScript("var "+Pf[0]); for(var Qf;Pf.length&&(Qf=Pf.shift());)!Pf.length&&q(Of)?Z[Qf]=Of:Z[Qf]&&Z[Qf]!==Object.prototype[Qf]?Z=Z[Qf]:Z=Z[Qf]={};

}catch(e){_._DumpException(e)}
}).call(this,this.content_ads_contributor_ContributorGdprCachedJs);
// Google Inc.

//# sourceURL=/_/mss/boq-content-ads-contributor/_/js/k=boq-content-ads-contributor.ContributorGdprCachedJs.es.Jnhl5BV3Mso.O/rt=j/d=1/rs=AJlcJMx-XlJGlDJzhXTVFVmVfTmaPfbw7Q/m=gdprcached
__TqF050x7LrBv__(window, 'W1tbbnVsbCxudWxsLG51bGwsImh0dHBzOi8vZnVuZGluZ2Nob2ljZXMuZ29vZ2xlLmNvbS9mL0FHU0tXeFc0VThiZWNIX2Zrc0pIdWVlbm9WNGd3S2I5THh5TUIwOFI4MDlWeHVxbVRKZWFhNHhUYjFnbGdHd1RqWnRpcmlGQXRYa2RpZEVcdTAwM2QiXQosWyJDVUlEIiwyMDAsMywiQVFBQiIsInhqRCszbi8yZGc5ZjVVRkFJVWYrNHZoWkdRU2MzRUtoZGV0d2EyN2RWMExMYjdaYXo3d0JGL1NYZ3ROTDgwZmp0eXMrcGpnYTVjWitoVGd4aURIYkprNllzWGR2bjNSRmpDMG5vdXhoeitpbCtxbEJwSUdKRVRuYUN4RnRkUXFaNndWdHVlUTY0a1k3QkNMWGRwazdmYkhmd1dhMmdPYWZFNGNWZ241WHR6RW5taUxITFFITSs3VFUvaXJCeExwK0trQ1JKbFJXa3RzT1VzZWxmdGxkYVRvNDNRZzhGTlpxUFluMlpTL1oyMS8xZER1OEloNUdTQ01JVUw1M2dyUlhDS2JxaDhvU3VqSmJDVGNCUVgxb1dRVzd5ZC9GU1R0OWZEOEdIODVMVWxraHR3WEJkcXJka2cyb1RWRHF4alhHd1pzZjZBZkxiM0k0Mk92WVlqSkhtUVx1MDAzZFx1MDAzZCIsIjI1MDIyOWYyMDI0YTZjN2IiLCJyZWZjb24iLDkwMDAwMCw2MDAwMCw2MDAwMCw4NjQwMDAwMCwiUCwxNTM5NTA2NTYyMzg1OkFMSEdMdVFBQUFBUFVDd3hOVE01TlRBMk5UWXlNemcxZXJ2eXNsQXVXWC8xejNhL3lrclcxZzMwbkdLdDc5dmxaVW91MGdRaDlsWkhEZlVaNHBzZHdIaHhCWGJkV2UxNE44dTFmVHBJcTd3U2hTVkl4KzdENmxOU013Z3BmTGpxMklCajBSNG9yblFOSEZxNUU3WlhTY1ZnSjBsYnA5Yi9jbmRaejkwSFp0L0tOd1RYWmdzcHJ3dm56SU0vZU54Rk1ybnloNDJBdlI4WXcySWZGcXBiZVUyeUs2L1ZxeXhvbmUzS1FTREhVKzJ0eThHY0lRWG9kV2FSdGhEcXJMd0kvVGFHeGV4UmxQNWgwUTM2aHNUekFTbTZzWVFMWUV0dUlqbkQ0ZG5OVDl4RHhmRXI5Q0hKSlJkVEowZFBQZUZGZFduZVd4N0ZLMDVXQ2FkY1FmTi9FcThSVWg1am9qQjh4RXBxN3RoN0xzSU80VFgvZG5ySVZnXHUwMDNkXHUwMDNkIiwyNTkyMDAwXQosW251bGwsbnVsbCwiaHR0cHM6Ly9zdXBwb3J0Lmdvb2dsZS5jb20vY29udHJpYnV0b3IvYW5zd2VyLzc2ODc5ODUiXQosW251bGwsbnVsbCxudWxsLCJodHRwczovL2Z1bmRpbmdjaG9pY2VzLmdvb2dsZS5jb20vbC9BR1NLV3hYZ2JMaFhuZTZ4MVgzOEJEWlJkWTFqZmhnUVJONEZ2RHExbnlDMjFmSjNFV3hvdG5SRldJeDRsNDZTSnlLclkxVHNndzR1UnlnXHUwMDNkIl0KXQosbnVsbCwwLCIyNTAyMjlmMjAyNGE2YzdiIl0K');