"use strict";this.content_ads_contributor_ContributorTargetingClientJs=this.content_ads_contributor_ContributorTargetingClientJs||{};(function(_){var window=this;
try{
var aa=function(a){for(;a&&"."===a[0];)a=a.substring(1);return a},ca=function(a,b,c){a=a instanceof k?new k(a):new k(a,void 0);var d=a.c+"/",e=b;null===e&&(e=new ba);b=n(e,1)?n(e,1):"";e=n(e,2)?n(e,2):"";if(b.includes(":D:"))throw Error("j`"+b);a.c=d+(b+(""===e?"":":D:"+e))+"/"+c;return a},da=function(a){var b=0;return function(){return b<a.length?{done:!1,value:a[b++]}:{done:!0}}},ea=function(a){var b="undefined"!=typeof window.Symbol&&window.Symbol.iterator&&a[window.Symbol.iterator];return b?b.call(a):
{next:da(a)}},fa="function"==typeof Object.defineProperties?Object.defineProperty:function(a,b,c){a!=Array.prototype&&a!=Object.prototype&&(a[b]=c.value)},ha="undefined"!=typeof window&&window===this?this:"undefined"!=typeof window.global&&null!=window.global?window.global:this,ia=function(a,b){if(b){var c=ha;a=a.split(".");for(var d=0;d<a.length-1;d++){var e=a[d];e in c||(c[e]={});c=c[e]}a=a[a.length-1];d=c[a];b=b(d);b!=d&&null!=b&&fa(c,a,{configurable:!0,writable:!0,value:b})}};
ia("Object.is",function(a){return a?a:function(a,c){return a===c?0!==a||1/a===1/c:a!==a&&c!==c}});ia("String.prototype.includes",function(a){return a?a:function(a,c){if(null==this)throw new TypeError("a`includes");if(a instanceof RegExp)throw new TypeError("b`includes");return-1!==this.indexOf(a,c||0)}});
var ja=ja||{},p=this,r=function(a){return void 0!==a},t=function(a){return"string"==typeof a},u=function(){},ka=function(a){var b=typeof a;if("object"==b)if(a){if(a instanceof Array)return"array";if(a instanceof Object)return b;var c=Object.prototype.toString.call(a);if("[object Window]"==c)return"object";if("[object Array]"==c||"number"==typeof a.length&&"undefined"!=typeof a.splice&&"undefined"!=typeof a.propertyIsEnumerable&&!a.propertyIsEnumerable("splice"))return"array";if("[object Function]"==
c||"undefined"!=typeof a.call&&"undefined"!=typeof a.propertyIsEnumerable&&!a.propertyIsEnumerable("call"))return"function"}else return"null";else if("function"==b&&"undefined"==typeof a.call)return"object";return b},v=function(a){return"array"==ka(a)},la=function(a){var b=ka(a);return"array"==b||"object"==b&&"number"==typeof a.length},w=function(a){return"function"==ka(a)},ma=function(a){var b=typeof a;return"object"==b&&null!=a||"function"==b},na="closure_uid_"+(1E9*Math.random()>>>0),oa=0,pa=function(a,
b,c){return a.call.apply(a.bind,arguments)},qa=function(a,b,c){if(!a)throw Error();if(2<arguments.length){var d=Array.prototype.slice.call(arguments,2);return function(){var c=Array.prototype.slice.call(arguments);Array.prototype.unshift.apply(c,d);return a.apply(b,c)}}return function(){return a.apply(b,arguments)}},x=function(a,b,c){Function.prototype.bind&&-1!=Function.prototype.bind.toString().indexOf("native code")?x=pa:x=qa;return x.apply(null,arguments)},ra=Date.now||function(){return+new Date},
sa=function(a,b){a=a.split(".");var c=p;a[0]in c||"undefined"==typeof c.execScript||c.execScript("var "+a[0]);for(var d;a.length&&(d=a.shift());)!a.length&&r(b)?c[d]=b:c[d]&&c[d]!==Object.prototype[d]?c=c[d]:c=c[d]={}},y=function(a,b){function c(){}c.prototype=b.prototype;a.K=b.prototype;a.prototype=new c;a.prototype.constructor=a;a.V=function(a,c,f){for(var d=Array(arguments.length-2),e=2;e<arguments.length;e++)d[e-2]=arguments[e];return b.prototype[c].apply(a,d)}};
var z=function(a){if(Error.captureStackTrace)Error.captureStackTrace(this,z);else{var b=Error().stack;b&&(this.stack=b)}a&&(this.message=String(a))};y(z,Error);z.prototype.name="CustomError";var ta;var ua=Array.prototype.indexOf?function(a,b){return Array.prototype.indexOf.call(a,b,void 0)}:function(a,b){if(t(a))return t(b)&&1==b.length?a.indexOf(b,0):-1;for(var c=0;c<a.length;c++)if(c in a&&a[c]===b)return c;return-1},va=Array.prototype.forEach?function(a,b,c){Array.prototype.forEach.call(a,b,c)}:function(a,b,c){for(var d=a.length,e=t(a)?a.split(""):a,f=0;f<d;f++)f in e&&b.call(c,e[f],f,a)},wa=Array.prototype.some?function(a,b){return Array.prototype.some.call(a,b,void 0)}:function(a,b){for(var c=
a.length,d=t(a)?a.split(""):a,e=0;e<c;e++)if(e in d&&b.call(void 0,d[e],e,a))return!0;return!1},ya=function(a){a:{var b=xa;for(var c=a.length,d=t(a)?a.split(""):a,e=0;e<c;e++)if(e in d&&b.call(void 0,d[e],e,a)){b=e;break a}b=-1}return 0>b?null:t(a)?a.charAt(b):a[b]},za=function(a,b){b=ua(a,b);var c;(c=0<=b)&&Array.prototype.splice.call(a,b,1);return c},Aa=function(a){return Array.prototype.concat.apply([],arguments)},Ba=function(a){var b=a.length;if(0<b){for(var c=Array(b),d=0;d<b;d++)c[d]=a[d];return c}return[]},
Ca=function(a,b){for(var c=1;c<arguments.length;c++){var d=arguments[c];if(la(d)){var e=a.length||0,f=d.length||0;a.length=e+f;for(var g=0;g<f;g++)a[e+g]=d[g]}else a.push(d)}},A=function(a,b,c){return 2>=arguments.length?Array.prototype.slice.call(a,b):Array.prototype.slice.call(a,b,c)},Da=function(a,b){for(var c=[],d=0;d<b;d++)c[d]=a;return c},Ea=function(a){for(var b=[],c=0;c<arguments.length;c++){var d=arguments[c];if(v(d))for(var e=0;e<d.length;e+=8192)for(var f=Ea.apply(null,A(d,e,e+8192)),g= 0;g<f.length;g++)b.push(f[g]);else b.push(d)}return b};
var Fa=String.prototype.trim?function(a){return a.trim()}:function(a){return/^[\s\xa0]*([\s\S]*?)[\s\xa0]*$/.exec(a)[1]},Ga=function(a,b){return a<b?-1:a>b?1:0},Ha=function(a){var b=t(void 0)?"undefined".replace(/([-()\[\]{}+?*.$\^|,:#<!\\])/g,"\\$1").replace(/\x08/g,"\\x08"):"\\s";return a.replace(new RegExp("(^"+(b?"|["+b+"]+":"")+")([a-z])","g"),function(a,b,e){return b+e.toUpperCase()})};
var C;a:{var Ia=p.navigator;if(Ia){var Ja=Ia.userAgent;if(Ja){C=Ja;break a}}C=""}var D=function(a){return-1!=C.indexOf(a)};var Ka="constructor hasOwnProperty isPrototypeOf propertyIsEnumerable toLocaleString toString valueOf".split(" "),La=function(a,b){for(var c,d,e=1;e<arguments.length;e++){d=arguments[e];for(c in d)a[c]=d[c];for(var f=0;f<Ka.length;f++)c=Ka[f],Object.prototype.hasOwnProperty.call(d,c)&&(a[c]=d[c])}};
var Ma=function(a){Ma[" "](a);return a};Ma[" "]=u;var Oa=function(a,b){var c=Na;return Object.prototype.hasOwnProperty.call(c,a)?c[a]:c[a]=b(a)};var Pa=D("Opera"),E=D("Trident")||D("MSIE"),Qa=D("Edge"),Ra=D("Gecko")&&!(-1!=C.toLowerCase().indexOf("webkit")&&!D("Edge"))&&!(D("Trident")||D("MSIE"))&&!D("Edge"),Sa=-1!=C.toLowerCase().indexOf("webkit")&&!D("Edge"),Ta=function(){var a=p.document;return a?a.documentMode:void 0},Ua;
a:{var Va="",Wa=function(){var a=C;if(Ra)return/rv:([^\);]+)(\)|;)/.exec(a);if(Qa)return/Edge\/([\d\.]+)/.exec(a);if(E)return/\b(?:MSIE|rv)[: ]([^\);]+)(\)|;)/.exec(a);if(Sa)return/WebKit\/(\S+)/.exec(a);if(Pa)return/(?:Version)[ \/]?(\S+)/.exec(a)}();Wa&&(Va=Wa?Wa[1]:"");if(E){var Xa=Ta();if(null!=Xa&&Xa>(0,window.parseFloat)(Va)){Ua=String(Xa);break a}}Ua=Va}
var Ya=Ua,Na={},Za=function(a){return Oa(a,function(){for(var b=0,c=Fa(String(Ya)).split("."),d=Fa(String(a)).split("."),e=Math.max(c.length,d.length),f=0;0==b&&f<e;f++){var g=c[f]||"",h=d[f]||"";do{g=/(\d*)(\D*)(.*)/.exec(g)||["","","",""];h=/(\d*)(\D*)(.*)/.exec(h)||["","","",""];if(0==g[0].length&&0==h[0].length)break;b=Ga(0==g[1].length?0:(0,window.parseInt)(g[1],10),0==h[1].length?0:(0,window.parseInt)(h[1],10))||Ga(0==g[2].length,0==h[2].length)||Ga(g[2],h[2]);g=g[3];h=h[3]}while(0==b)}return 0<= b})},$a;var ab=p.document;$a=ab&&E?Ta()||("CSS1Compat"==ab.compatMode?(0,window.parseInt)(Ya,10):5):void 0;
var bb=D("Safari")&&!((D("Chrome")||D("CriOS"))&&!D("Edge")||D("Coast")||D("Opera")||D("Edge")||D("Silk")||D("Android"))&&!(D("iPhone")&&!D("iPod")&&!D("iPad")||D("iPad")||D("iPod"));var cb=null,db=null,eb=Ra||Sa&&!bb||Pa||!bb&&!E&&"function"==typeof p.atob,gb=function(a){if(eb)return p.atob(a);var b="";fb(a,function(a){b+=String.fromCharCode(a)});return b},hb=function(a){var b=[];fb(a,function(a){b.push(a)});return b},fb=function(a,b){function c(b){for(;d<a.length;){var c=a.charAt(d++),e=db[c];if(null!=e)return e;if(!/^[\s\xa0]*$/.test(c))throw Error("c`"+c);}return b}ib();for(var d=0;;){var e=c(-1),f=c(0),g=c(64),h=c(64);if(64===h&&-1===e)break;b(e<<2|f>>4);64!=g&&(b(f<<4&240|
g>>2),64!=h&&b(g<<6&192|h))}},ib=function(){if(!cb){cb={};db={};for(var a=0;65>a;a++)cb[a]="ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/=".charAt(a),db[cb[a]]=a,62<=a&&(db["ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789-_.".charAt(a)]=a)}};
var F=function(a){var b=ba;this.b=a;this.f=b;this.a={};this.c=!0;if(0<this.b.length){for(a=0;a<this.b.length;a++){b=this.b[a];var c=b[0];this.a[c.toString()]=new jb(c,b[1])}this.c=!0}};F.prototype.B=function(){if(this.c){if(this.f){var a=this.a,b;for(b in a)if(Object.prototype.hasOwnProperty.call(a,b)){var c=a[b].a;c&&c.B()}}}else{this.b.length=0;a=G(this);a.sort();for(b=0;b<a.length;b++){var d=this.a[a[b]];(c=d.a)&&c.B();this.b.push([d.key,d.value])}this.c=!0}return this.b};
var kb=function(a){this.a=0;this.b=a};kb.prototype.next=function(){return this.a<this.b.length?{done:!1,value:this.b[this.a++]}:{done:!0,value:void 0}};"undefined"!=typeof window.Symbol&&(kb.prototype[window.Symbol.iterator]=function(){return this});var lb=function(a){var b=[],c=G(a);c.sort();for(var d=0;d<c.length;d++){var e=a.a[c[d]];b.push([e.key,e.value])}return b};F.prototype.entries=function(){var a=[],b=G(this);b.sort();for(var c=0;c<b.length;c++){var d=this.a[b[c]];a.push([d.key,mb(this,d)])}return new kb(a)};
F.prototype.keys=function(){var a=[],b=G(this);b.sort();for(var c=0;c<b.length;c++)a.push(this.a[b[c]].key);return new kb(a)};F.prototype.values=function(){var a=[],b=G(this);b.sort();for(var c=0;c<b.length;c++)a.push(mb(this,this.a[b[c]]));return new kb(a)};F.prototype.forEach=function(a,b){var c=G(this);c.sort();for(var d=0;d<c.length;d++){var e=this.a[c[d]];a.call(b,mb(this,e),e.key,this)}};
F.prototype.set=function(a,b){var c=new jb(a);this.f?(c.a=b,c.value=b.B()):c.value=b;this.a[a.toString()]=c;this.c=!1;return this};var mb=function(a,b){return a.f?(b.a||(b.a=new a.f(b.value)),b.a):b.value};F.prototype.get=function(a){if(a=this.a[a.toString()])return mb(this,a)};F.prototype.has=function(a){return a.toString()in this.a};var G=function(a){a=a.a;var b=[],c;for(c in a)Object.prototype.hasOwnProperty.call(a,c)&&b.push(c);return b},jb=function(a,b){this.key=a;this.value=b;this.a=void 0};
var H=function(){},nb="function"==typeof window.Uint8Array,pb=function(a,b,c){a.a=null;b||(b=[]);a.i=void 0;a.f=-1;a.b=b;a:{if(b=a.b.length){--b;var d=a.b[b];if(!(null===d||"object"!=typeof d||v(d)||nb&&d instanceof window.Uint8Array)){a.g=b-a.f;a.c=d;break a}}a.g=Number.MAX_VALUE}a.h={};if(c)for(b=0;b<c.length;b++)d=c[b],d<a.g?(d+=a.f,a.b[d]=a.b[d]||J):(ob(a),a.c[d]=a.c[d]||J)},J=[],ob=function(a){var b=a.g+a.f;a.b[b]||(a.c=a.b[b]={})},n=function(a,b){if(b<a.g){b+=a.f;var c=a.b[b];return c===J?a.b[b]=
[]:c}if(a.c)return c=a.c[b],c===J?a.c[b]=[]:c},qb=function(a,b,c){a.a||(a.a={});if(!a.a[c]){var d=n(a,c);d&&(a.a[c]=new b(d))}return a.a[c]},sb=function(a){var b=rb;a.a||(a.a={});if(!a.a[1]){if(1<a.g){var c=1+a.f;var d=a.b[c];c=d===J?a.b[c]=[]:d}else d=a.c[1],c=d===J?a.c[1]=[]:d;d=[];for(var e=0;e<c.length;e++)d[e]=new b(c[e]);a.a[1]=d}b=a.a[1];b==J&&(b=a.a[1]=[]);return b},tb=function(a){if(a.a)for(var b in a.a){var c=a.a[b];if(v(c))for(var d=0;d<c.length;d++)c[d]&&c[d].B();else c&&c.B()}}; H.prototype.B=function(){tb(this);return this.b};H.prototype.toString=function(){tb(this);return this.b.toString()};
var ub=function(a){pb(this,a,null)};y(ub,H);var vb=function(){this.b=-1};var wb=function(){this.b=64;this.a=[];this.j=[];this.l=[];this.i=[];this.i[0]=128;for(var a=1;a<this.b;++a)this.i[a]=0;this.h=this.f=0;this.reset()};y(wb,vb);wb.prototype.reset=function(){this.a[0]=1732584193;this.a[1]=4023233417;this.a[2]=2562383102;this.a[3]=271733878;this.a[4]=3285377520;this.h=this.f=0};
var xb=function(a,b,c){c||(c=0);var d=a.l;if(t(b))for(var e=0;16>e;e++)d[e]=b.charCodeAt(c)<<24|b.charCodeAt(c+1)<<16|b.charCodeAt(c+2)<<8|b.charCodeAt(c+3),c+=4;else for(e=0;16>e;e++)d[e]=b[c]<<24|b[c+1]<<16|b[c+2]<<8|b[c+3],c+=4;for(e=16;80>e;e++){var f=d[e-3]^d[e-8]^d[e-14]^d[e-16];d[e]=(f<<1|f>>>31)&4294967295}b=a.a[0];c=a.a[1];var g=a.a[2],h=a.a[3],l=a.a[4];for(e=0;80>e;e++){if(40>e)if(20>e){f=h^c&(g^h);var m=1518500249}else f=c^g^h,m=1859775393;else 60>e?(f=c&g|h&(c|g),m=2400959708):(f=c^g^
h,m=3395469782);f=(b<<5|b>>>27)+f+l+m+d[e]&4294967295;l=h;h=g;g=(c<<30|c>>>2)&4294967295;c=b;b=f}a.a[0]=a.a[0]+b&4294967295;a.a[1]=a.a[1]+c&4294967295;a.a[2]=a.a[2]+g&4294967295;a.a[3]=a.a[3]+h&4294967295;a.a[4]=a.a[4]+l&4294967295};
wb.prototype.c=function(a,b){if(null!=a){r(b)||(b=a.length);for(var c=b-this.b,d=0,e=this.j,f=this.f;d<b;){if(0==f)for(;d<=c;)xb(this,a,d),d+=this.b;if(t(a))for(;d<b;){if(e[f]=a.charCodeAt(d),++f,++d,f==this.b){xb(this,e);f=0;break}}else for(;d<b;)if(e[f]=a[d],++f,++d,f==this.b){xb(this,e);f=0;break}}this.f=f;this.h+=b}};
wb.prototype.g=function(){var a=[],b=8*this.h;56>this.f?this.c(this.i,56-this.f):this.c(this.i,this.b-(this.f-56));for(var c=this.b-1;56<=c;c--)this.j[c]=b&255,b/=256;xb(this,this.j);for(c=b=0;5>c;c++)for(var d=24;0<=d;d-=8)a[b]=this.a[c]>>d&255,++b;return a};
var yb=function(a,b){this.c=a;this.f=b;this.b=0;this.a=null};yb.prototype.get=function(){if(0<this.b){this.b--;var a=this.a;this.a=a.next;a.next=null}else a=this.c();return a};var zb=function(a,b){a.f(b);100>a.b&&(a.b++,b.next=a.a,a.a=b)};var Ab=function(a){p.setTimeout(function(){throw a;},0)},Bb,Cb=function(){var a=p.MessageChannel;"undefined"===typeof a&&"undefined"!==typeof window&&window.postMessage&&window.addEventListener&&!D("Presto")&&(a=function(){var a=window.document.createElement("IFRAME");a.style.display="none";a.src="";window.document.documentElement.appendChild(a);var b=a.contentWindow;a=b.document;a.open();a.write("");a.close();var c="callImmediate"+Math.random(),d="file:"==b.location.protocol?"*":b.location.protocol+
"//"+b.location.host;a=x(function(a){if(("*"==d||a.origin==d)&&a.data==c)this.port1.onmessage()},this);b.addEventListener("message",a,!1);this.port1={};this.port2={postMessage:function(){b.postMessage(c,d)}}});if("undefined"!==typeof a&&!D("Trident")&&!D("MSIE")){var b=new a,c={},d=c;b.port1.onmessage=function(){if(r(c.next)){c=c.next;var a=c.N;c.N=null;a()}};return function(a){d.next={N:a};d=d.next;b.port2.postMessage(0)}}return"undefined"!==typeof window.document&&"onreadystatechange"in window.document.createElement("SCRIPT")? function(a){var b=window.document.createElement("SCRIPT");b.onreadystatechange=function(){b.onreadystatechange=null;b.parentNode.removeChild(b);b=null;a();a=null};window.document.documentElement.appendChild(b)}:function(a){p.setTimeout(a,0)}};
var Db=function(){this.b=this.a=null},Fb=new yb(function(){return new Eb},function(a){a.reset()});Db.prototype.add=function(a,b){var c=Fb.get();c.set(a,b);this.b?this.b.next=c:this.a=c;this.b=c};var Hb=function(){var a=Gb,b=null;a.a&&(b=a.a,a.a=a.a.next,a.a||(a.b=null),b.next=null);return b},Eb=function(){this.next=this.b=this.a=null};Eb.prototype.set=function(a,b){this.a=a;this.b=b;this.next=null};Eb.prototype.reset=function(){this.next=this.b=this.a=null};
var Lb=function(a,b){Ib||Jb();Kb||(Ib(),Kb=!0);Gb.add(a,b)},Ib,Jb=function(){if(p.Promise&&p.Promise.resolve){var a=p.Promise.resolve(void 0);Ib=function(){a.then(Mb)}}else Ib=function(){var a=Mb;!w(p.setImmediate)||p.Window&&p.Window.prototype&&!D("Edge")&&p.Window.prototype.setImmediate==p.setImmediate?(Bb||(Bb=Cb()),Bb(a)):p.setImmediate(a)}},Kb=!1,Gb=new Db,Mb=function(){for(var a;a=Hb();){try{a.a.call(a.b)}catch(b){Ab(b)}zb(Fb,a)}Kb=!1};
var Nb=function(a){a.prototype.then=a.prototype.then;a.prototype.$goog_Thenable=!0},Ob=function(a){if(!a)return!1;try{return!!a.$goog_Thenable}catch(b){return!1}};var K=function(a,b){this.a=0;this.i=void 0;this.f=this.b=this.c=null;this.g=this.h=!1;if(a!=u)try{var c=this;a.call(b,function(a){Pb(c,2,a)},function(a){Pb(c,3,a)})}catch(d){Pb(this,3,d)}},Qb=function(){this.next=this.c=this.b=this.f=this.a=null;this.g=!1};Qb.prototype.reset=function(){this.c=this.b=this.f=this.a=null;this.g=!1};var Rb=new yb(function(){return new Qb},function(a){a.reset()}),Sb=function(a,b,c){var d=Rb.get();d.f=a;d.b=b;d.c=c;return d};
K.prototype.then=function(a,b,c){return Tb(this,w(a)?a:null,w(b)?b:null,c)};Nb(K);K.prototype.cancel=function(a){0==this.a&&Lb(function(){var b=new Ub(a);Vb(this,b)},this)};
var Vb=function(a,b){if(0==a.a)if(a.c){var c=a.c;if(c.b){for(var d=0,e=null,f=null,g=c.b;g&&(g.g||(d++,g.a==a&&(e=g),!(e&&1<d)));g=g.next)e||(f=g);e&&(0==c.a&&1==d?Vb(c,b):(f?(d=f,d.next==c.f&&(c.f=d),d.next=d.next.next):Wb(c),Xb(c,e,3,b)))}a.c=null}else Pb(a,3,b)},Zb=function(a,b){a.b||2!=a.a&&3!=a.a||Yb(a);a.f?a.f.next=b:a.b=b;a.f=b},Tb=function(a,b,c,d){var e=Sb(null,null,null);e.a=new K(function(a,g){e.f=b?function(c){try{var e=b.call(d,c);a(e)}catch(m){g(m)}}:a;e.b=c?function(b){try{var e=c.call(d,
b);!r(e)&&b instanceof Ub?g(b):a(e)}catch(m){g(m)}}:g});e.a.c=a;Zb(a,e);return e.a};K.prototype.l=function(a){this.a=0;Pb(this,2,a)};K.prototype.m=function(a){this.a=0;Pb(this,3,a)};
var Pb=function(a,b,c){if(0==a.a){a===c&&(b=3,c=new TypeError("d"));a.a=1;a:{var d=c,e=a.l,f=a.m;if(d instanceof K){Zb(d,Sb(e||u,f||null,a));var g=!0}else if(Ob(d))d.then(e,f,a),g=!0;else{if(ma(d))try{var h=d.then;if(w(h)){$b(d,h,e,f,a);g=!0;break a}}catch(l){f.call(a,l);g=!0;break a}g=!1}}g||(a.i=c,a.a=b,a.c=null,Yb(a),3!=b||c instanceof Ub||ac(a,c))}},$b=function(a,b,c,d,e){var f=!1,g=function(a){f||(f=!0,c.call(e,a))},h=function(a){f||(f=!0,d.call(e,a))};try{b.call(a,g,h)}catch(l){h(l)}},Yb=function(a){a.h||
(a.h=!0,Lb(a.j,a))},Wb=function(a){var b=null;a.b&&(b=a.b,a.b=b.next,b.next=null);a.b||(a.f=null);return b};K.prototype.j=function(){for(var a;a=Wb(this);)Xb(this,a,this.a,this.i);this.h=!1};
var Xb=function(a,b,c,d){if(3==c&&b.b&&!b.g)for(;a&&a.g;a=a.c)a.g=!1;if(b.a)b.a.c=null,bc(b,c,d);else try{b.g?b.f.call(b.c):bc(b,c,d)}catch(e){cc.call(null,e)}zb(Rb,b)},bc=function(a,b,c){2==b?a.f.call(a.c,c):a.b&&a.b.call(a.c,c)},ac=function(a,b){a.g=!0;Lb(function(){a.g&&cc.call(null,b)})},cc=Ab,Ub=function(a){z.call(this,a)};y(Ub,z);Ub.prototype.name="cancel";
/*
 Portions of this code are from MochiKit, received by
 The Closure Authors under the MIT license. All other code is Copyright
 2005-2009 The Closure Authors. All Rights Reserved.
*/
var dc=function(a,b){this.g=[];this.u=a;this.s=b||null;this.f=this.a=!1;this.b=void 0;this.l=this.w=this.i=!1;this.h=0;this.c=null;this.j=0};dc.prototype.cancel=function(a){if(this.a)this.b instanceof dc&&this.b.cancel();else{if(this.c){var b=this.c;delete this.c;a?b.cancel(a):(b.j--,0>=b.j&&b.cancel())}this.u?this.u.call(this.s,this):this.l=!0;if(!this.a){a=new ec(this);if(this.a){if(!this.l)throw new fc(this);this.l=!1}this.a=!0;this.b=a;this.f=!0;gc(this)}}};
dc.prototype.m=function(a,b){this.i=!1;this.a=!0;this.b=b;this.f=!a;gc(this)};var hc=function(a,b,c){a.g.push([b,c,void 0]);a.a&&gc(a)};dc.prototype.then=function(a,b,c){var d,e,f=new K(function(a,b){d=a;e=b});hc(this,d,function(a){a instanceof ec?f.cancel():e(a)});return f.then(a,b,c)};Nb(dc);
var ic=function(a){return wa(a.g,function(a){return w(a[1])})},gc=function(a){if(a.h&&a.a&&ic(a)){var b=a.h,c=jc[b];c&&(p.clearTimeout(c.a),delete jc[b]);a.h=0}a.c&&(a.c.j--,delete a.c);b=a.b;for(var d=c=!1;a.g.length&&!a.i;){var e=a.g.shift(),f=e[0],g=e[1];e=e[2];if(f=a.f?g:f)try{var h=f.call(e||a.s,b);r(h)&&(a.f=a.f&&(h==b||h instanceof Error),a.b=b=h);if(Ob(b)||"function"===typeof p.Promise&&b instanceof p.Promise)d=!0,a.i=!0}catch(l){b=l,a.f=!0,ic(a)||(c=!0)}}a.b=b;d&&(h=x(a.m,a,!0),d=x(a.m,a,
!1),b instanceof dc?(hc(b,h,d),b.w=!0):b.then(h,d));c&&(b=new kc(b),jc[b.a]=b,a.h=b.a)},fc=function(){z.call(this)};y(fc,z);fc.prototype.message="Deferred has already fired";fc.prototype.name="AlreadyCalledError";var ec=function(){z.call(this)};y(ec,z);ec.prototype.message="Deferred was canceled";ec.prototype.name="CanceledError";var kc=function(a){this.a=p.setTimeout(x(this.c,this),0);this.b=a};kc.prototype.c=function(){delete jc[this.a];throw this.b;};var jc={};
/*

 Copyright 2013 Google Inc. All rights reserved.
 Licensed under the Apache License, Version 2.0 (the "License");
 you may not use this file except in compliance with the License.
 You may obtain a copy of the License at

   http://www.apache.org/licenses/LICENSE-2.0

 Unless required by applicable law or agreed to in writing, software
 distributed under the License is distributed on an "AS IS" BASIS,
 WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 See the License for the specific language governing permissions and
 limitations under the License.
*/
var lc=function(a){z.call(this,a)};y(lc,z);var mc=function(a){z.call(this,a)};y(mc,lc);/*

 Copyright 2012 Google Inc. All rights reserved.
 Licensed under the Apache License, Version 2.0 (the "License");
 you may not use this file except in compliance with the License.
 You may obtain a copy of the License at

   http://www.apache.org/licenses/LICENSE-2.0

 Unless required by applicable law or agreed to in writing, software
 distributed under the License is distributed on an "AS IS" BASIS,
 WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 See the License for the specific language governing permissions and
 limitations under the License.
*/
var nc=function(a){var b=[];va(a,function(a){b.push(a>>>24&255);b.push(a>>>16&255);b.push(a>>>8&255);b.push(a&255)});return b},oc=function(a){for(var b=1,c=0;c<a.length;c++){var d=a[c];b&=("number"==typeof d&&0<=d&&255>=d&&0==d-Math.floor(d))|0}return 1==b};
var pc=function(){this.a=null},qc=function(){this.a=null};y(qc,pc);var rc=function(){};/*

 Copyright 2014 Google Inc. All rights reserved.
 Licensed under the Apache License, Version 2.0 (the "License");
 you may not use this file except in compliance with the License.
 You may obtain a copy of the License at

   http://www.apache.org/licenses/LICENSE-2.0

 Unless required by applicable law or agreed to in writing, software
 distributed under the License is distributed on an "AS IS" BASIS,
 WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 See the License for the specific language governing permissions and
 limitations under the License.
*/
var sc=function(a,b){return(-(a>b|0)|0)&(a^b)^b};/*

 Copyright 2011 Google Inc. All rights reserved.
 Licensed under the Apache License, Version 2.0 (the "License");
 you may not use this file except in compliance with the License.
 You may obtain a copy of the License at

   http://www.apache.org/licenses/LICENSE-2.0

 Unless required by applicable law or agreed to in writing, software
 distributed under the License is distributed on an "AS IS" BASIS,
 WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 See the License for the specific language governing permissions and
 limitations under the License.
*/
var L=function(a){this.a=[];if(r(a)){if(!(w(p.Uint8Array)&&a instanceof window.Uint8Array||oc(a)))throw new mc("Input should be a byte array.");for(var b=a.length,c=Array((b+2)/3|0),d=0;0<=b;b-=3)c[d++]=a[b-1]&255|(a[b-2]&255)<<8|(a[b-3]&255)<<16;this.a=c}this.b=0},M=function(a){var b=new L;b.a.length=a;return b},tc=function(a){var b=new L;b.a=Ba(a);return b},uc=function(a){if(0>a||281474976710656<a)throw new mc("Argument must be a valid integer.");var b=new L;do b.a.push(a&16777215),a=Math.floor(a/
16777216);while(0<a);return b},vc=function(a,b,c){c=-c|0;for(var d=sc(a.a.length,b.a.length),e=M(d),f=0;f<d;++f)e.a[f]=c&(a.a[f]^b.a[f]);for(f=0;f<d;++f)e.a[f]^=b.a[f];return e},wc=function(a){for(var b=a.a.length,c=0,d=Array(3*b);0<b;--b)d[c++]=a.a[b-1]>>>16&255,d[c++]=a.a[b-1]>>>8&255,d[c++]=a.a[b-1]&255;for(c=b=a=0;c<d.length;++c)b|=d[c],a+=!b&!d[c];return d.slice(a-(1&!b))};
L.prototype.toString=function(){var a=[],b=this,c=uc(1E6);do b=xc(b,c),a.unshift(b.O.a[0]),b=b.U,yc(b);while(!zc(b));return a.map(function(a,b){return 0==b||1E6<a?""+a:("000000"+a).slice(-6)}).join("")};var yc=function(a){for(var b=0,c=0,d=a.a.length-1;0<d;--d)c|=a.a[d],b+=!c&!a.a[d];a.a.length-=b;return a},Ac=function(a){if(0==a.b){for(var b=0,c=0,d=a.a.length-1;0<d;--d)c|=a.a[d],b+=!c&!a.a[d];c=a.a.length-b;b=24*c;c=a.a[c-1];for(c|=!c;0==(c&8388608);)c<<=1,--b;a=a.b=b}else a=a.b;return a};
L.prototype.add=function(a){for(var b=sc(this.a.length,a.a.length),c=M(b+1),d=0,e=0;e<b;++e)d+=(this.a[e]|0)+(a.a[e]|0),c.a[e]=d&16777215,d>>=24;c.a[b]=d;return c};
var xc=function(a,b){var c=Ac(b),d=(c+24-1)/24|0;c=24*d-c;b=Bc(b,c);var e=vc(tc(a.a),Bc(a,c),0==c|0);a=vc(Cc,M(e.a.length+1),0>=e.a.length+1-d|0);e.a.push(0);for(var f=e.a.length-d-1;0<=f;f--){var g=b.a.length,h=16777216*e.a[g+f]+e.a[g+f-1];var l=b.a[g-1];var m=Math.floor(h/l);l=m-(16777216==m|m*(b.a[g-2]|0)>16777216*(h-m*l)+(e.a[g+f-2]|0));g=0;a.a[f]=l;for(h=0;h<=d;h++)g+=e.a[h+f]-(b.a[h]|0)*l,e.a[h+f]=g&16777215,g=Math.floor(g/16777216);l=g;g=0;a.a[f]+=l;for(h=0;h<=d;h++)g+=e.a[h+f]+(b.a[h]&l),
e.a[h+f]=g&16777215,g>>=24}if(0>c||23<c)throw new mc("Illegal shift value.");h=e.a.length;b=M(h);f=(1<<c)-1;g=0;for(--h;0<=h;h--)b.a[h]=g+(e.a[h]>>c),g=(e.a[h]&f)<<24-c;c=M(d);for(e=0;e<d;e++)c.a[e]=b.a[e]|0;e=c;yc(a);return{U:a,O:e}},zc=function(a){for(var b=Cc,c=0,d=0,e=0,f=0,g=sc(a.a.length,b.a.length)-1;0<=g;--g){var h=a.a[g]|0,l=b.a[g]|0;d|=h<l;c|=h>l&!d;e|=h>l;f|=h<l&!e}return 0==c-f};
L.prototype.and=function(a){for(var b=sc(this.a.length,a.a.length),c=M(b);0<=b;--b)c.a[b]=(this.a[b]|0)&(a.a[b]|0);return c};L.prototype.or=function(a){for(var b=sc(this.a.length,a.a.length),c=M(b);0<=b;--b)c.a[b]=this.a[b]|0|a.a[b]|0;return c};L.prototype.xor=function(a){for(var b=sc(this.a.length,a.a.length),c=M(b);0<=b;--b)c.a[b]=(this.a[b]|0)^(a.a[b]|0);return c}; var Bc=function(a,b){if(0>b||23<b)throw new mc("Illegal shift value.");for(var c=a.a.length,d=M(c+1),e=(1<<b)-1,f=(1<<24-b)-1,g=0,h=0;h<c;h++)d.a[h]=((a.a[h]&f)<<b)+g,g=a.a[h]>>24-b&e;d.a[c]=g;return yc(d)},Cc=uc(0);uc(1);uc(2);
var Ec=function(a,b){L.call(this,a);yc(this);a=1;for(var c=this.a[0],d=1;16777216>d;d<<=1)a*c&d&&(a|=d);this.f=16777216-a;if(r(b))b=new L(b);else{b=this.a.length;a=M(2*b+1);for(c=0;c<2*b;++c)a.a[c]=0;a.a[2*b]=1;b=xc(a,this).O}this.g=b;this.c=Dc(this,this.g)};y(Ec,L);
Ec.prototype.pow=function(a,b){a=new L(a);b instanceof L&&(b=wc(b));var c=N(this,a,this.g);a=Array(16);a[0]=this.c;for(var d=1;16>d;++d)a[d]=N(this,c,a[d-1]);c=M(this.a.length);d=tc(this.c.a);for(var e=b.length,f=0;f<e;++f)N(this,d,d,c),N(this,c,c,d),N(this,d,d,c),N(this,c,c,d),N(this,d,a[b[f]>>4&15],c),N(this,c,c,d),N(this,d,d,c),N(this,c,c,d),N(this,d,d,c),N(this,c,a[b[f]&15],d);Dc(this,d,c);return wc(c)};
var Dc=function(a,b,c){var d=a.a.length;c=c||M(d);for(var e=0;e<d;++e)c.a[e]=b.a[e];for(e=0;e<d;++e){b=a;var f=c,g=f.a[0],h=g*b.f&16777215;g+=h*b.a[0];for(var l=1,m=b.a.length;l<m;++l)g=(g/16777216|0)+f.a[l]+h*b.a[l],f.a[l-1]=g&16777215;f.a[l-1]=g/16777216|0}Fc(a,c,d);return c},N=function(a,b,c,d){var e=a.a.length;d=d||M(e);for(var f=0;f<e;++f)d.a[f]=0;for(f=0;f<e;++f){var g=a,h=b.a[f]|0,l=c,m=d,q=h*l.a[0]+m.a[0],B=(q&16777215)*g.f&16777215;q+=B*g.a[0];for(var I=1,xe=g.a.length;I<xe;++I)q=(q/16777216|
0)+h*(l.a[I]|0)+m.a[I]+B*g.a[I],m.a[I-1]=q&16777215;m.a[I-1]=q/16777216|0}Fc(a,d,e);return d},Fc=function(a,b,c){for(var d=0,e=0;e<c;++e)d+=b.a[e]-a.a[e],b.a[e]=d&16777215,d>>=24;var f=d>>24;for(e=d=0;e<c;++e)d+=b.a[e]+(a.a[e]&f),b.a[e]=d&16777215,d>>=24};
var Gc=function(a,b,c){this.c=a;this.f=this.b=b;this.a=null;this.modulusLength=0;this.a=new Ec(a,c);this.modulusLength=Math.ceil(Ac(this.a)/8)};y(Gc,rc);var Jc=function(a,b){this.b=64;this.h=p.Uint8Array?new window.Uint8Array(this.b):Array(this.b);this.i=this.f=0;this.a=[];this.l=a;this.j=b;this.m=p.Int32Array?new window.Int32Array(64):Array(64);r(Hc)||(p.Int32Array?Hc=new window.Int32Array(Ic):Hc=Ic);this.reset()},Hc;y(Jc,vb);var Kc=Aa(128,Da(0,63));Jc.prototype.reset=function(){this.i=this.f=0;this.a=p.Int32Array?new window.Int32Array(this.j):Ba(this.j)};
var Lc=function(a){for(var b=a.h,c=a.m,d=0,e=0;e<b.length;)c[d++]=b[e]<<24|b[e+1]<<16|b[e+2]<<8|b[e+3],e=4*d;for(b=16;64>b;b++){e=c[b-15]|0;d=c[b-2]|0;var f=(c[b-16]|0)+((e>>>7|e<<25)^(e>>>18|e<<14)^e>>>3)|0,g=(c[b-7]|0)+((d>>>17|d<<15)^(d>>>19|d<<13)^d>>>10)|0;c[b]=f+g|0}d=a.a[0]|0;e=a.a[1]|0;var h=a.a[2]|0,l=a.a[3]|0,m=a.a[4]|0,q=a.a[5]|0,B=a.a[6]|0;f=a.a[7]|0;for(b=0;64>b;b++){var I=((d>>>2|d<<30)^(d>>>13|d<<19)^(d>>>22|d<<10))+(d&e^d&h^e&h)|0;g=m&q^~m&B;f=f+((m>>>6|m<<26)^(m>>>11|m<<21)^(m>>>
25|m<<7))|0;g=g+(Hc[b]|0)|0;g=f+(g+(c[b]|0)|0)|0;f=B;B=q;q=m;m=l+g|0;l=h;h=e;e=d;d=g+I|0}a.a[0]=a.a[0]+d|0;a.a[1]=a.a[1]+e|0;a.a[2]=a.a[2]+h|0;a.a[3]=a.a[3]+l|0;a.a[4]=a.a[4]+m|0;a.a[5]=a.a[5]+q|0;a.a[6]=a.a[6]+B|0;a.a[7]=a.a[7]+f|0};
Jc.prototype.c=function(a,b){r(b)||(b=a.length);var c=0,d=this.f;if(t(a))for(;c<b;)this.h[d++]=a.charCodeAt(c++),d==this.b&&(Lc(this),d=0);else if(la(a))for(;c<b;){var e=a[c++];if(!("number"==typeof e&&0<=e&&255>=e&&e==(e|0)))throw Error("e");this.h[d++]=e;d==this.b&&(Lc(this),d=0)}else throw Error("f");this.f=d;this.i+=b};
Jc.prototype.g=function(){var a=[],b=8*this.i;56>this.f?this.c(Kc,56-this.f):this.c(Kc,this.b-(this.f-56));for(var c=63;56<=c;c--)this.h[c]=b&255,b/=256;Lc(this);for(c=b=0;c<this.l;c++)for(var d=24;0<=d;d-=8)a[b++]=this.a[c]>>d&255;return a};
var Ic=[1116352408,1899447441,3049323471,3921009573,961987163,1508970993,2453635748,2870763221,3624381080,310598401,607225278,1426881987,1925078388,2162078206,2614888103,3248222580,3835390401,4022224774,264347078,604807628,770255983,1249150122,1555081692,1996064986,2554220882,2821834349,2952996808,3210313671,3336571891,3584528711,113926993,338241895,666307205,773529912,1294757372,1396182291,1695183700,1986661051,2177026350,2456956037,2730485921,2820302411,3259730800,3345764771,3516065817,3600352804, 4094571909,275423344,430227734,506948616,659060556,883997877,958139571,1322822218,1537002063,1747873779,1955562222,2024104815,2227730452,2361852424,2428436474,2756734187,3204031479,3329325298];
var Nc=function(){Jc.call(this,8,Mc)};y(Nc,Jc);var Mc=[1779033703,3144134277,1013904242,2773480762,1359893119,2600822924,528734635,1541459225];var O=function(a,b){this.b=a|0;this.a=b|0},Rc=function(a){return 0<a?0x7fffffffffffffff<=a?Oc:new O(a,a/4294967296):0>a?-9223372036854775808>=a?Pc:P(new O(-a,-a/4294967296)):Qc},Q=function(a,b){return new O(a,b)},Qc=Q(0,0),Sc=Q(1,0),Tc=Q(-1,-1),Oc=Q(4294967295,2147483647),Pc=Q(0,2147483648),Uc=function(a){return 4294967296*a.a+(a.b>>>0)};
O.prototype.toString=function(a){a=a||10;if(2>a||36<a)throw Error("g`"+a);var b=this.a>>21;if(0==b||-1==b&&(0!=this.b||-2097152!=this.a))return b=Uc(this),10==a?""+b:b.toString(a);b=14-(a>>2);var c=Math.pow(a,b),d=Q(c,c/4294967296);c=Vc(this,d);d=Math.abs(Uc(this.add(P(Wc(c,d)))));var e=10==a?""+d:d.toString(a);e.length<b&&(e="0000000000000".substr(e.length-b)+e);d=Uc(c);return(10==a?d:d.toString(a))+e};
var Xc=function(a){return 0==a.b&&0==a.a},Yc=function(a,b){return a.b==b.b&&a.a==b.a},Zc=function(a,b){return a.a==b.a?a.b==b.b?0:a.b>>>0>b.b>>>0?1:-1:a.a>b.a?1:-1},P=function(a){var b=~a.b+1|0;return Q(b,~a.a+!b|0)};O.prototype.add=function(a){var b=this.a>>>16,c=this.a&65535,d=this.b>>>16,e=a.a>>>16,f=a.a&65535,g=a.b>>>16;a=(this.b&65535)+(a.b&65535);g=(a>>>16)+(d+g);d=g>>>16;d+=c+f;b=(d>>>16)+(b+e)&65535;return Q((g&65535)<<16|a&65535,b<<16|d&65535)};
var Wc=function(a,b){if(Xc(a))return a;if(Xc(b))return b;var c=a.a>>>16,d=a.a&65535,e=a.b>>>16;a=a.b&65535;var f=b.a>>>16,g=b.a&65535,h=b.b>>>16;b=b.b&65535;var l=a*b;var m=(l>>>16)+e*b;var q=m>>>16;m=(m&65535)+a*h;q+=m>>>16;q+=d*b;var B=q>>>16;q=(q&65535)+e*h;B+=q>>>16;q=(q&65535)+a*g;B=B+(q>>>16)+(c*b+d*h+e*g+a*f)&65535;return Q((m&65535)<<16|l&65535,B<<16|q&65535)},Vc=function(a,b){if(Xc(b))throw Error("h");if(0>a.a){if(Yc(a,Pc)){if(Yc(b,Sc)||Yc(b,Tc))return Pc;if(Yc(b,Pc))return Sc;var c=1;if(0==
c)c=a;else{var d=a.a;c=32>c?Q(a.b>>>c|d<<32-c,d>>c):Q(d>>c-32,0<=d?0:-1)}c=Vc(c,b);d=1;if(0!=d){var e=c.b;c=32>d?Q(e<<d,c.a<<d|e>>>32-d):Q(0,e<<d-32)}if(Yc(c,Qc))return 0>b.a?Sc:Tc;a=a.add(P(Wc(b,c)));return c.add(Vc(a,b))}return 0>b.a?Vc(P(a),P(b)):P(Vc(P(a),b))}if(Xc(a))return Qc;if(0>b.a)return Yc(b,Pc)?Qc:P(Vc(a,P(b)));for(d=Qc;0<=Zc(a,b);){c=Math.max(1,Math.floor(Uc(a)/Uc(b)));e=Math.ceil(Math.log(c)/Math.LN2);e=48>=e?1:Math.pow(2,e-48);for(var f=Rc(c),g=Wc(f,b);0>g.a||0<Zc(g,a);)c-=e,f=Rc(c), g=Wc(f,b);Xc(f)&&(f=Sc);d=d.add(f);a=a.add(P(g))}return d};O.prototype.and=function(a){return Q(this.b&a.b,this.a&a.a)};O.prototype.or=function(a){return Q(this.b|a.b,this.a|a.a)};O.prototype.xor=function(a){return Q(this.b^a.b,this.a^a.a)};
for(var $c=[1116352408,3609767458,1899447441,602891725,3049323471,3964484399,3921009573,2173295548,961987163,4081628472,1508970993,3053834265,2453635748,2937671579,2870763221,3664609560,3624381080,2734883394,310598401,1164996542,607225278,1323610764,1426881987,3590304994,1925078388,4068182383,2162078206,991336113,2614888103,633803317,3248222580,3479774868,3835390401,2666613458,4022224774,944711139,264347078,2341262773,604807628,2007800933,770255983,1495990901,1249150122,1856431235,1555081692,3175218132,
1996064986,2198950837,2554220882,3999719339,2821834349,766784016,2952996808,2566594879,3210313671,3203337956,3336571891,1034457026,3584528711,2466948901,113926993,3758326383,338241895,168717936,666307205,1188179964,773529912,1546045734,1294757372,1522805485,1396182291,2643833823,1695183700,2343527390,1986661051,1014477480,2177026350,1206759142,2456956037,344077627,2730485921,1290863460,2820302411,3158454273,3259730800,3505952657,3345764771,106217008,3516065817,3606008344,3600352804,1432725776,4094571909,
1467031594,275423344,851169720,430227734,3100823752,506948616,1363258195,659060556,3750685593,883997877,3785050280,958139571,3318307427,1322822218,3812723403,1537002063,2003034995,1747873779,3602036899,1955562222,1575990012,2024104815,1125592928,2227730452,2716904306,2361852424,442776044,2428436474,593698344,2756734187,3733110249,3204031479,2999351573,3329325298,3815920427,3391569614,3928383900,3515267271,566280711,3940187606,3454069534,4118630271,4000239992,116418474,1914138554,174292421,2731055270,
289380356,3203993006,460393269,320620315,685471733,587496836,852142971,1086792851,1017036298,365543100,1126000580,2618297676,1288033470,3409855158,1501505948,4234509866,1607167915,987167468,1816402316,1246189591],ad=[],bd=0;bd<$c.length;bd+=2)ad.push(new O($c[bd+1],$c[bd]));
var cd=function(){this.b=-1};y(cd,vb);cd.prototype.reset=function(){this.a.reset()};cd.prototype.g=function(){return this.a.g()};cd.prototype.c=function(a,b){this.a.c(a,b)};cd.prototype.hash=function(a){this.reset();this.c(a);return this.g()};var dd=function(){this.b=-1;this.a=new Nc;this.b=this.a.b};y(dd,cd);dd.prototype.f="SHA256";var ed=function(a){z.call(this,a)};y(ed,z);var fd={MD5:[48,32,48,12,6,8,42,134,72,134,247,13,2,5,5,0,4,16],RIPEMD160:[48,33,48,9,6,5,43,36,3,2,1,5,0,4,20],SHA1:[48,33,48,9,6,5,43,14,3,2,26,5,0,4,20],SHA224:[48,45,48,13,6,9,96,134,72,1,101,3,4,2,4,5,0,4,28],SHA256:[48,49,48,13,6,9,96,134,72,1,101,3,4,2,1,5,0,4,32],SHA384:[48,65,48,13,6,9,96,134,72,1,101,3,4,2,2,5,0,4,48],SHA512:[48,81,48,13,6,9,96,134,72,1,101,3,4,2,3,5,0,4,64]};
var gd=function(a,b,c,d){Gc.call(this,a,b,c);this.g=d||new dd};y(gd,Gc);var hd=function(a,b,c,d){this.a=null;this.b=new gd(a,b,c,d)};y(hd,qc);var id=function(a){this.a=a};var jd=function(a,b){this.a=new id(new hd(a,b))};var kd=function(a,b,c,d,e){this.a="U";this.b=0;a&&(a=a.split(","))&&2==a.length&&(this.a=a[0],this.b=(0,window.parseInt)(a[1],10));if(0>=b||0>=c||0>=d)throw Error("i");this.h=b;this.c=c;this.g=d;this.f=e},ld=function(a){switch(a.a){case "Y":return a.h;case "N":return a.c;case "P":return a.f;default:return a.g}},md=function(a,b,c,d,e,f){this.g=new jd(hb(a),hb(b));this.f=c;this.a=d;this.c=e;this.b=f},nd=function(a,b,c){for(var d=a.g,e=[],f=0,g=0;g<c.length;g++){var h=c.charCodeAt(g);255<h&&(e[f++]=
h&255,h>>=8);e[f++]=h}b=hb(b.substr(b.indexOf(":")+1));d=d.a;c=d.a;c.a||(f=new wb,f.c(nc([c.b.c.length])),f.c(c.b.c),f.c(nc([c.b.b.length])),f.c(c.b.b),f=f.g(),g=Array(5),g[0]=0,g[1]=f[0],g[2]=f[1],g[3]=f[2],g[4]=f[3],c.a=g);c=c.a;b:if(f=A(b,0,c.length),la(c)&&la(f)&&c.length==f.length){g=c.length;for(h=0;h<g;h++)if(c[h]!==f[h]){f=!1;break b}f=!0}else f=!1;if(f){f=c.length+4;c=A(b,c.length,f);g=[];for(h=0;h<c.length;h+=4)g.push((c[h+3]|c[h+2]<<8|c[h+1]<<16|c[h]<<24)>>>0);h=g[0];if(f+h>b.length)e=
null;else{c=A(b,f,f+h);g=Ea(c,nc([e.length]),e,b[0]);d=d.a.b;e=d.a.pow(A(b,f+h),d.f);b=d.g;d=d.modulusLength-1;g=b.hash(g);f=[];if(!r(fd[b.f]))throw new ed("invalid hash for signature");Ca(f,fd[b.f]);Ca(f,g);b=f.length;if(d<b+11)throw new ed("intended encoded message length too short");b=[1].concat(Da(255,d-b-3+1)).concat([0]).concat(f);if(b.length===e.length&&oc(b)&&oc(e)){d=1;for(f=0;f<b.length;f++)d&=!(b[f]^e[f])|0;e=1==d}else e=!1;e=e?c:null}}else e=null;if(e)if(8192>=e.length)e=String.fromCharCode.apply(null, e);else{b="";for(d=0;d<e.length;d+=8192)b+=String.fromCharCode.apply(null,A(e,d,d+8192));e=b}else e=null;return new kd(e,a.f,a.a,a.c,a.b)};
var ba=function(a){pb(this,a,null)};y(ba,H);var od=function(a){var b=p.location.hostname;a=ea(a);for(var c=a.next();!c.done;c=a.next()){c=c.value;var d;if(!(d=b.toLowerCase()==c.toLowerCase())){var e="."+c;d=String(e).toLowerCase();e=String(b.substr(b.length-e.length,e.length)).toLowerCase();d=0==(d<e?-1:d==e?0:1)}if(d)return"."+c}return null};
var pd=function(){this.a=window.document||{cookie:""}};pd.prototype.set=function(a,b,c,d,e,f){if(/[;=\s]/.test(a))throw Error("k`"+a);if(/[;\r\n]/.test(b))throw Error("l`"+b);r(c)||(c=-1);e=e?";domain="+e:"";d=d?";path="+d:"";f=f?";secure":"";c=0>c?"":0==c?";expires="+(new Date(1970,1,1)).toUTCString():";expires="+(new Date(ra()+1E3*c)).toUTCString();this.a.cookie=a+"="+b+e+d+c+f};
pd.prototype.get=function(a,b){for(var c=a+"=",d=(this.a.cookie||"").split(";"),e=0,f;e<d.length;e++){f=Fa(d[e]);if(0==f.lastIndexOf(c,0))return f.substr(c.length);if(f==a)return""}return b};pd.prototype.v=function(){return qd(this).keys};pd.prototype.f=function(){return qd(this).values}; var qd=function(a){a=(a.a.cookie||"").split(";");for(var b=[],c=[],d,e,f=0;f<a.length;f++)e=Fa(a[f]),d=e.indexOf("="),-1==d?(b.push(""),c.push(e)):(b.push(e.substring(0,d)),c.push(e.substring(d+1)));return{keys:b,values:c}};
var rd=/^(?:([^:/?#.]+):)?(?:\/\/(?:([^/?#]*)@)?([^/#?]*?)(?::([0-9]+))?(?=[/#?]|$))?([^?#]+)?(?:\?([^#]*))?(?:#([\s\S]*))?$/,sd=function(a,b){if(a){a=a.split("&");for(var c=0;c<a.length;c++){var d=a[c].indexOf("="),e=null;if(0<=d){var f=a[c].substring(0,d);e=a[c].substring(d+1)}else f=a[c];b(f,e?(0,window.decodeURIComponent)(e.replace(/\+/g," ")):"")}}},td=/#|$/;
var ud=function(a,b,c){this.b=a;this.f=n(b,6);this.a=n(b,1);this.c=c;a=p.location.href;c=n(b,7);a:{for(var d=a.search(td),e=0,f=c.length;0<=(e=a.indexOf(c,e))&&e<d;){var g=a.charCodeAt(e-1);if(38==g||63==g)if(g=a.charCodeAt(e+f),!g||61==g||38==g||35==g){a=e;break a}e+=f+1}a=-1}this.h=0<=a;this.g=new md(n(b,5),n(b,4),n(b,8),n(b,9),n(b,10),n(b,11))},vd=function(a){var b=a.b.get(a.a);if(null!==a.c&&b){b=nd(a.g,b,a.f);if("Y"==b.a){if(b.b+ld(b)<ra()){b=a.b;var c=a.a;a=a.c;b.get(c);b.set(c,"",0,"/",a)}return!0}if("P"== b.a){if(!(b.b+ld(b)<ra()))return!0;b=a.b;c=a.a;a=a.c;b.get(c);b.set(c,"",0,"/",a)}}return!1},wd=function(a){if(null!==a.c){if(a.h)return!0;var b=a.b.get(a.a);return b?(a=nd(a.g,b,a.f),a.b+ld(a)<ra()||"P"==a.a):!0}return!1};
var yd=function(a){pb(this,a,xd)};y(yd,H);var rb=function(a){pb(this,a,null)};y(rb,H);var xd=[1];var zd=function(a){pb(this,a,null)};y(zd,H);var Ad=function(a){a.a||(a.a={});if(2 in a.a)a=a.a[2];else{var b=n(a,2);if(!b){var c=b=[];2<a.g?a.b[2+a.f]=c:(ob(a),a.c[2]=c)}a=a.a[2]=new F(b)}return a};var Bd;(Bd=!E)||(Bd=9<=Number($a));var Cd=Bd,Dd=E&&!Za("9"),Ed=function(){if(!p.addEventListener||!Object.defineProperty)return!1;var a=!1,b=Object.defineProperty({},"passive",{get:function(){a=!0}});try{p.addEventListener("test",u,b),p.removeEventListener("test",u,b)}catch(c){}return a}();
var Fd=function(){this.g=this.g;this.i=this.i};Fd.prototype.g=!1;Fd.prototype.c=function(){if(this.i)for(;this.i.length;)this.i.shift()()};var R=function(a,b){this.type=a;this.a=this.target=b;this.P=!0};R.prototype.b=function(){this.P=!1};var Hd=function(a,b){R.call(this,a?a.type:"");this.relatedTarget=this.a=this.target=null;this.button=this.screenY=this.screenX=this.clientY=this.clientX=0;this.key="";this.metaKey=this.shiftKey=this.altKey=this.ctrlKey=!1;this.pointerId=0;this.pointerType="";this.c=null;if(a){var c=this.type=a.type,d=a.changedTouches?a.changedTouches[0]:null;this.target=a.target||a.srcElement;this.a=b;if(b=a.relatedTarget){if(Ra){a:{try{Ma(b.nodeName);var e=!0;break a}catch(f){}e=!1}e||(b=null)}}else"mouseover"==
c?b=a.fromElement:"mouseout"==c&&(b=a.toElement);this.relatedTarget=b;null===d?(this.clientX=void 0!==a.clientX?a.clientX:a.pageX,this.clientY=void 0!==a.clientY?a.clientY:a.pageY,this.screenX=a.screenX||0,this.screenY=a.screenY||0):(this.clientX=void 0!==d.clientX?d.clientX:d.pageX,this.clientY=void 0!==d.clientY?d.clientY:d.pageY,this.screenX=d.screenX||0,this.screenY=d.screenY||0);this.button=a.button;this.key=a.key||"";this.ctrlKey=a.ctrlKey;this.altKey=a.altKey;this.shiftKey=a.shiftKey;this.metaKey=
a.metaKey;this.pointerId=a.pointerId||0;this.pointerType=t(a.pointerType)?a.pointerType:Gd[a.pointerType]||"";this.c=a;a.defaultPrevented&&this.b()}};y(Hd,R);var Gd={2:"touch",3:"pen",4:"mouse"};Hd.prototype.b=function(){Hd.K.b.call(this);var a=this.c;if(a.preventDefault)a.preventDefault();else if(a.returnValue=!1,Dd)try{if(a.ctrlKey||112<=a.keyCode&&123>=a.keyCode)a.keyCode=-1}catch(b){}};
var Id="closure_listenable_"+(1E6*Math.random()|0),Jd=function(a){return!(!a||!a[Id])},Kd=0;var Ld=function(a,b,c,d,e){this.listener=a;this.a=null;this.src=b;this.type=c;this.capture=!!d;this.J=e;this.key=++Kd;this.A=this.I=!1},Md=function(a){a.A=!0;a.listener=null;a.a=null;a.src=null;a.J=null};var Nd=function(a){this.src=a;this.a={};this.b=0};Nd.prototype.add=function(a,b,c,d,e){var f=a.toString();a=this.a[f];a||(a=this.a[f]=[],this.b++);var g=Od(a,b,d,e);-1<g?(b=a[g],c||(b.I=!1)):(b=new Ld(b,this.src,f,!!d,e),b.I=c,a.push(b));return b};
var Pd=function(a,b){var c=b.type;if(!(c in a.a))return!1;var d=za(a.a[c],b);d&&(Md(b),0==a.a[c].length&&(delete a.a[c],a.b--));return d},Qd=function(a,b){b=b&&b.toString();var c=0,d;for(d in a.a)if(!b||d==b){for(var e=a.a[d],f=0;f<e.length;f++)++c,Md(e[f]);delete a.a[d];a.b--}},Od=function(a,b,c,d){for(var e=0;e<a.length;++e){var f=a[e];if(!f.A&&f.listener==b&&f.capture==!!c&&f.J==d)return e}return-1};
var Rd="closure_lm_"+(1E6*Math.random()|0),Sd={},Td=0,Vd=function(a,b,c,d,e){if(d&&d.once)return Ud(a,b,c,d,e);if(v(b)){for(var f=0;f<b.length;f++)Vd(a,b[f],c,d,e);return null}c=Wd(c);return Jd(a)?a.o.add(String(b),c,!1,ma(d)?!!d.capture:!!d,e):Xd(a,b,c,!1,d,e)},Xd=function(a,b,c,d,e,f){if(!b)throw Error("m");var g=ma(e)?!!e.capture:!!e,h=Yd(a);h||(a[Rd]=h=new Nd(a));c=h.add(b,c,d,g,f);if(c.a)return c;d=Zd();c.a=d;d.src=a;d.listener=c;if(a.addEventListener)Ed||(e=g),void 0===e&&(e=!1),a.addEventListener(b.toString(),
d,e);else if(a.attachEvent)a.attachEvent($d(b.toString()),d);else if(a.addListener&&a.removeListener)a.addListener(d);else throw Error("n");Td++;return c},Zd=function(){var a=ae,b=Cd?function(c){return a.call(b.src,b.listener,c)}:function(c){c=a.call(b.src,b.listener,c);if(!c)return c};return b},Ud=function(a,b,c,d,e){if(v(b)){for(var f=0;f<b.length;f++)Ud(a,b[f],c,d,e);return null}c=Wd(c);return Jd(a)?a.o.add(String(b),c,!0,ma(d)?!!d.capture:!!d,e):Xd(a,b,c,!0,d,e)},be=function(a,b,c,d,e){if(v(b))for(var f=
0;f<b.length;f++)be(a,b[f],c,d,e);else(d=ma(d)?!!d.capture:!!d,c=Wd(c),Jd(a))?(a=a.o,b=String(b).toString(),b in a.a&&(f=a.a[b],c=Od(f,c,d,e),-1<c&&(Md(f[c]),Array.prototype.splice.call(f,c,1),0==f.length&&(delete a.a[b],a.b--)))):a&&(a=Yd(a))&&(b=a.a[b.toString()],a=-1,b&&(a=Od(b,c,d,e)),(c=-1<a?b[a]:null)&&ce(c))},ce=function(a){if("number"==typeof a||!a||a.A)return!1;var b=a.src;if(Jd(b))return Pd(b.o,a);var c=a.type,d=a.a;b.removeEventListener?b.removeEventListener(c,d,a.capture):b.detachEvent?
b.detachEvent($d(c),d):b.addListener&&b.removeListener&&b.removeListener(d);Td--;(c=Yd(b))?(Pd(c,a),0==c.b&&(c.src=null,b[Rd]=null)):Md(a);return!0},$d=function(a){return a in Sd?Sd[a]:Sd[a]="on"+a},ee=function(a,b,c,d){var e=!0;if(a=Yd(a))if(b=a.a[b.toString()])for(b=b.concat(),a=0;a<b.length;a++){var f=b[a];f&&f.capture==c&&!f.A&&(f=de(f,d),e=e&&!1!==f)}return e},de=function(a,b){var c=a.listener,d=a.J||a.src;a.I&&ce(a);return c.call(d,b)},ae=function(a,b){if(a.A)return!0;if(!Cd){if(!b)a:{b=["window",
"event"];for(var c=p,d=0;d<b.length;d++)if(c=c[b[d]],null==c){b=null;break a}b=c}d=b;b=new Hd(d,this);c=!0;if(!(0>d.keyCode||void 0!=d.returnValue)){a:{var e=!1;if(0==d.keyCode)try{d.keyCode=-1;break a}catch(g){e=!0}if(e||void 0==d.returnValue)d.returnValue=!0}d=[];for(e=b.a;e;e=e.parentNode)d.push(e);a=a.type;for(e=d.length-1;0<=e;e--){b.a=d[e];var f=ee(d[e],a,!0,b);c=c&&f}for(e=0;e<d.length;e++)b.a=d[e],f=ee(d[e],a,!1,b),c=c&&f}return c}return de(a,new Hd(b,this))},Yd=function(a){a=a[Rd];return a instanceof Nd?a:null},fe="__closure_events_fn_"+(1E9*Math.random()>>>0),Wd=function(a){if(w(a))return a;a[fe]||(a[fe]=function(b){return a.handleEvent(b)});return a[fe]};
var ge=function(){this.a=p.document||window.document};var he=function(){return Sa?"Webkit":Ra?"Moz":E?"ms":Pa?"O":null},ie=function(a,b){if(b&&a in b)return a;var c=he();return c?(c=c.toLowerCase(),a=c+Ha(a),!r(b)||a in b?a:null):null};var S=function(){Fd.call(this);this.o=new Nd(this);this.R=this;this.F=null};y(S,Fd);S.prototype[Id]=!0;S.prototype.removeEventListener=function(a,b,c,d){be(this,a,b,c,d)};
var T=function(a,b){var c,d=a.F;if(d)for(c=[];d;d=d.F)c.push(d);a=a.R;d=b.type||b;if(t(b))b=new R(b,a);else if(b instanceof R)b.target=b.target||a;else{var e=b;b=new R(d,a);La(b,e)}e=!0;if(c)for(var f=c.length-1;0<=f;f--){var g=b.a=c[f];e=je(g,d,!0,b)&&e}g=b.a=a;e=je(g,d,!0,b)&&e;e=je(g,d,!1,b)&&e;if(c)for(f=0;f<c.length;f++)g=b.a=c[f],e=je(g,d,!1,b)&&e};S.prototype.c=function(){S.K.c.call(this);this.o&&Qd(this.o,void 0);this.F=null}; var je=function(a,b,c,d){b=a.o.a[String(b)];if(!b)return!0;b=b.concat();for(var e=!0,f=0;f<b.length;++f){var g=b[f];if(g&&!g.A&&g.capture==c){var h=g.listener,l=g.J||g.src;g.I&&Pd(a.o,g);e=!1!==h.call(l,d)&&e}}return e&&0!=d.P};
var le=function(a){var b=ke;return function(){var c=this||p;c=c.closure_memoize_cache_||(c.closure_memoize_cache_={});var d=b(a[na]||(a[na]=++oa),arguments);return c.hasOwnProperty(d)?c[d]:c[d]=a.apply(this,arguments)}},ke=function(a,b){a=[a];for(var c=b.length-1;0<=c;--c)a.push(typeof b[c],b[c]);return a.join("\x0B")};
var U=function(a){S.call(this);a||(a=ta||(ta=new ge));this.a=a;if(this.f=this.j())this.h=Vd(this.a.a,this.f,x(this.m,this))};y(U,S);U.prototype.j=le(function(){var a=!!this.b(),b="hidden"!=this.b();if(a){var c;b?c=((he()||"")+"visibilitychange").toLowerCase():c="visibilitychange";a=c}else a=null;return a});U.prototype.b=le(function(){return ie("hidden",this.a.a)});U.prototype.l=le(function(){return ie("visibilityState",this.a.a)});var me=function(a){return!!a.a.a[a.b()]}; U.prototype.m=function(){var a=this.b()?this.a.a[this.l()]:null;a=new ne(me(this),a);T(this,a)};U.prototype.c=function(){ce(this.h);U.K.c.call(this)};var ne=function(){R.call(this,"visibilitychange")};y(ne,R);
var oe=function(){};oe.prototype.a=null;var qe=function(a){var b;(b=a.a)||(b={},pe(a)&&(b[0]=!0,b[1]=!0),b=a.a=b);return b};var re,se=function(){};y(se,oe);var te=function(a){return(a=pe(a))?new window.ActiveXObject(a):new window.XMLHttpRequest},pe=function(a){if(!a.b&&"undefined"==typeof window.XMLHttpRequest&&"undefined"!=typeof window.ActiveXObject){for(var b=["MSXML2.XMLHTTP.6.0","MSXML2.XMLHTTP.3.0","MSXML2.XMLHTTP","Microsoft.XMLHTTP"],c=0;c<b.length;c++){var d=b[c];try{return new window.ActiveXObject(d),a.b=d}catch(e){}}throw Error("o");}return a.b};re=new se;
var V=function(a,b){this.b={};this.a=[];this.c=0;var c=arguments.length;if(1<c){if(c%2)throw Error("p");for(var d=0;d<c;d+=2)this.set(arguments[d],arguments[d+1])}else if(a)if(a instanceof V)for(c=a.v(),d=0;d<c.length;d++)this.set(c[d],a.get(c[d]));else for(d in a)this.set(d,a[d])};V.prototype.f=function(){ue(this);for(var a=[],b=0;b<this.a.length;b++)a.push(this.b[this.a[b]]);return a};V.prototype.v=function(){ue(this);return this.a.concat()};
var ue=function(a){if(a.c!=a.a.length){for(var b=0,c=0;b<a.a.length;){var d=a.a[b];W(a.b,d)&&(a.a[c++]=d);b++}a.a.length=c}if(a.c!=a.a.length){var e={};for(c=b=0;b<a.a.length;)d=a.a[b],W(e,d)||(a.a[c++]=d,e[d]=1),b++;a.a.length=c}};V.prototype.get=function(a,b){return W(this.b,a)?this.b[a]:b};V.prototype.set=function(a,b){W(this.b,a)||(this.c++,this.a.push(a));this.b[a]=b};V.prototype.forEach=function(a,b){for(var c=this.v(),d=0;d<c.length;d++){var e=c[d],f=this.get(e);a.call(b,f,e,this)}}; var W=function(a,b){return Object.prototype.hasOwnProperty.call(a,b)};
var ve=function(a,b,c){if(w(a))c&&(a=x(a,c));else if(a&&"function"==typeof a.handleEvent)a=x(a.handleEvent,a);else throw Error("q");return 2147483647<Number(b)?-1:p.setTimeout(a,b||0)};var X=function(a){S.call(this);this.headers=new V;this.m=a||null;this.b=!1;this.l=this.a=null;this.w="";this.f=this.u=this.h=this.s=!1;this.G=0;this.j=null;this.L="";this.C=this.D=!1};y(X,S);var we=/^https?$/i,ye=["POST","PUT"],ze=[],Be=function(a,b,c){var d=new X;ze.push(d);b&&d.o.add("complete",b,!1,void 0,void 0);d.o.add("ready",d.S,!0,void 0,void 0);d.D=!0;Ae(d,a,c)};X.prototype.S=function(){this.g||(this.g=!0,this.c());za(ze,this)};
var Ae=function(a,b,c){if(a.a)throw Error("r`"+a.w+"`"+b);c=c?c.toUpperCase():"GET";a.w=b;a.s=!1;a.b=!0;a.a=a.m?te(a.m):te(re);a.l=a.m?qe(a.m):qe(re);a.a.onreadystatechange=x(a.H,a);try{a.u=!0,a.a.open(c,String(b),!0),a.u=!1}catch(f){Ce(a);return}b=new V(a.headers);var d=ya(b.v()),e=p.FormData&&!1;!(0<=ua(ye,c))||d||e||b.set("Content-Type","application/x-www-form-urlencoded;charset=utf-8");b.forEach(function(a,b){this.a.setRequestHeader(b,a)},a);a.L&&(a.a.responseType=a.L);"withCredentials"in a.a&&
a.a.withCredentials!==a.D&&(a.a.withCredentials=a.D);try{De(a),0<a.G&&(a.C=Ee(a.a),a.C?(a.a.timeout=a.G,a.a.ontimeout=x(a.M,a)):a.j=ve(a.M,a.G,a)),a.h=!0,a.a.send(""),a.h=!1}catch(f){Ce(a)}},Ee=function(a){return E&&Za(9)&&"number"==typeof a.timeout&&r(a.ontimeout)},xa=function(a){return"content-type"==a.toLowerCase()};X.prototype.M=function(){"undefined"!=typeof ja&&this.a&&(T(this,"timeout"),this.abort(8))};
var Ce=function(a){a.b=!1;a.a&&(a.f=!0,a.a.abort(),a.f=!1);Fe(a);Ge(a)},Fe=function(a){a.s||(a.s=!0,T(a,"complete"),T(a,"error"))};X.prototype.abort=function(){this.a&&this.b&&(this.b=!1,this.f=!0,this.a.abort(),this.f=!1,T(this,"complete"),T(this,"abort"),Ge(this))};X.prototype.c=function(){this.a&&(this.b&&(this.b=!1,this.f=!0,this.a.abort(),this.f=!1),Ge(this,!0));X.K.c.call(this)};X.prototype.H=function(){this.g||(this.u||this.h||this.f?He(this):this.T())};X.prototype.T=function(){He(this)};
var He=function(a){if(a.b&&"undefined"!=typeof ja&&(!a.l[1]||4!=(a.a?a.a.readyState:0)||2!=Ie(a)))if(a.h&&4==(a.a?a.a.readyState:0))ve(a.H,0,a);else if(T(a,"readystatechange"),4==(a.a?a.a.readyState:0)){a.b=!1;try{Je(a)?(T(a,"complete"),T(a,"success")):Fe(a)}finally{Ge(a)}}},Ge=function(a,b){if(a.a){De(a);var c=a.a,d=a.l[0]?u:null;a.a=null;a.l=null;b||T(a,"ready");try{c.onreadystatechange=d}catch(e){}}},De=function(a){a.a&&a.C&&(a.a.ontimeout=null);a.j&&(p.clearTimeout(a.j),a.j=null)},Je=function(a){var b=
Ie(a);a:switch(b){case 200:case 201:case 202:case 204:case 206:case 304:case 1223:var c=!0;break a;default:c=!1}if(!c){if(b=0===b)a=String(a.w).match(rd)[1]||null,!a&&p.self&&p.self.location&&(a=p.self.location.protocol,a=a.substr(0,a.length-1)),b=!we.test(a?a.toLowerCase():"");c=b}return c},Ie=function(a){try{return 2<(a.a?a.a.readyState:0)?a.a.status:-1}catch(b){return-1}};
var k=function(a,b){this.g=this.j=this.f="";this.i=null;this.h=this.c="";this.b=!1;if(a instanceof k){this.b=r(b)?b:a.b;Ke(this,a.f);this.j=a.j;this.g=a.g;Le(this,a.i);this.c=a.c;b=a.a;var c=new Y;c.c=b.c;b.a&&(c.a=new V(b.a),c.b=b.b);Me(this,c);this.h=a.h}else a&&(c=String(a).match(rd))?(this.b=!!b,Ke(this,c[1]||"",!0),this.j=Ne(c[2]||""),this.g=Ne(c[3]||"",!0),Le(this,c[4]),this.c=Ne(c[5]||"",!0),Me(this,c[6]||"",!0),this.h=Ne(c[7]||"")):(this.b=!!b,this.a=new Y(null,this.b))};
k.prototype.toString=function(){var a=[],b=this.f;b&&a.push(Oe(b,Pe,!0),":");var c=this.g;if(c||"file"==b)a.push("//"),(b=this.j)&&a.push(Oe(b,Pe,!0),"@"),a.push((0,window.encodeURIComponent)(String(c)).replace(/%25([0-9a-fA-F]{2})/g,"%$1")),c=this.i,null!=c&&a.push(":",String(c));if(c=this.c)this.g&&"/"!=c.charAt(0)&&a.push("/"),a.push(Oe(c,"/"==c.charAt(0)?Qe:Re,!0));(c=this.a.toString())&&a.push("?",c);(c=this.h)&&a.push("#",Oe(c,Se));return a.join("")};
var Ke=function(a,b,c){a.f=c?Ne(b,!0):b;a.f&&(a.f=a.f.replace(/:$/,""))},Le=function(a,b){if(b){b=Number(b);if((0,window.isNaN)(b)||0>b)throw Error("s`"+b);a.i=b}else a.i=null},Me=function(a,b,c){b instanceof Y?(a.a=b,Te(a.a,a.b)):(c||(b=Oe(b,Ue)),a.a=new Y(b,a.b))},Ne=function(a,b){return a?b?(0,window.decodeURI)(a.replace(/%25/g,"%2525")):(0,window.decodeURIComponent)(a):""},Oe=function(a,b,c){return t(a)?(a=(0,window.encodeURI)(a).replace(b,Ve),c&&(a=a.replace(/%25([0-9a-fA-F]{2})/g,"%$1")),a):
null},Ve=function(a){a=a.charCodeAt(0);return"%"+(a>>4&15).toString(16)+(a&15).toString(16)},Pe=/[#\/\?@]/g,Re=/[#\?:]/g,Qe=/[#\?]/g,Ue=/[#\?@]/g,Se=/#/g,Y=function(a,b){this.b=this.a=null;this.c=a||null;this.g=!!b},Z=function(a){a.a||(a.a=new V,a.b=0,a.c&&sd(a.c,function(b,c){a.add((0,window.decodeURIComponent)(b.replace(/\+/g," ")),c)}))};Y.prototype.add=function(a,b){Z(this);this.c=null;a=We(this,a);var c=this.a.get(a);c||this.a.set(a,c=[]);c.push(b);this.b+=1;return this};
var Xe=function(a,b){Z(a);b=We(a,b);W(a.a.b,b)&&(a.c=null,a.b-=a.a.get(b).length,a=a.a,W(a.b,b)&&(delete a.b[b],a.c--,a.a.length>2*a.c&&ue(a)))},Ye=function(a,b){Z(a);b=We(a,b);return W(a.a.b,b)};Y.prototype.forEach=function(a,b){Z(this);this.a.forEach(function(c,d){va(c,function(c){a.call(b,c,d,this)},this)},this)};Y.prototype.v=function(){Z(this);for(var a=this.a.f(),b=this.a.v(),c=[],d=0;d<b.length;d++)for(var e=a[d],f=0;f<e.length;f++)c.push(b[d]);return c};
Y.prototype.f=function(a){Z(this);var b=[];if(t(a))Ye(this,a)&&(b=Aa(b,this.a.get(We(this,a))));else{a=this.a.f();for(var c=0;c<a.length;c++)b=Aa(b,a[c])}return b};Y.prototype.set=function(a,b){Z(this);this.c=null;a=We(this,a);Ye(this,a)&&(this.b-=this.a.get(a).length);this.a.set(a,[b]);this.b+=1;return this};Y.prototype.get=function(a,b){if(!a)return b;a=this.f(a);return 0<a.length?String(a[0]):b};
Y.prototype.toString=function(){if(this.c)return this.c;if(!this.a)return"";for(var a=[],b=this.a.v(),c=0;c<b.length;c++){var d=b[c],e=(0,window.encodeURIComponent)(String(d));d=this.f(d);for(var f=0;f<d.length;f++){var g=e;""!==d[f]&&(g+="="+(0,window.encodeURIComponent)(String(d[f])));a.push(g)}}return this.c=a.join("&")};
var We=function(a,b){b=String(b);a.g&&(b=b.toLowerCase());return b},Te=function(a,b){b&&!a.g&&(Z(a),a.c=null,a.a.forEach(function(a,b){var c=b.toLowerCase();b!=c&&(Xe(this,b),Xe(this,c),0<a.length&&(this.c=null,this.a.set(We(this,c),Ba(a)),this.b+=a.length))},a));a.g=b};
/*

Math.uuid.js (v1.4)
http://www.broofa.com
mailto:robert@broofa.com
Copyright (c) 2010 Robert Kieffer
Dual licensed under the MIT and GPL licenses.
*/
var Ze="0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz".split(""),$e=function(){for(var a=Array(36),b=0,c,d=0;36>d;d++)8==d||13==d||18==d||23==d?a[d]="-":14==d?a[d]="4":(2>=b&&(b=33554432+16777216*Math.random()|0),c=b&15,b>>=4,a[d]=Ze[19==d?c&3|8:c]);return a.join("")};
var af=function(a){var b=qb(a,ub,1);this.a=new U;this.m=new window.MutationObserver(this.i.bind(this));this.b=null;this.h=this.g=!1;this.l=new pd;this.F=n(b,1);this.w=n(b,13);this.s=(this.c=od(lb(Ad(a)).map(function(a){return a[0]})))?Ad(a).get(aa(this.c)):new ba;this.f=new ud(this.l,b,this.c);this.H=sb(qb(a,yd,3));this.G=$e();this.j=ca(n(a,4),this.s,"checksub");this.D=ca(n(a,4),this.s,"clientevent")};af.prototype.start=function(){vd(this.f)&&bf(this);wd(this.f)&&cf(this)};
af.prototype.reset=function(){this.b=null;this.h=this.g=!1;var a=this.a;if(a)if(Jd(a))a.o&&Qd(a.o,"visibilitychange");else if(a=Yd(a)){var b=0,c="visibilitychange".toString(),d;for(d in a.a)if(!c||d==c)for(var e=a.a[d].concat(),f=0;f<e.length;++f)ce(e[f])&&++b}this.m.disconnect()};
var bf=function(a){try{a.m.observe(window.document.documentElement,{attributes:!0,childList:!0,subtree:!0})}catch(b){}a.i();a.a&&a.a.b()?(Vd(a.a,"visibilitychange",a.u,!1,a),me(a.a)||df(a)):a.h||(ef(a,3),a.h=!0)},cf=function(a){Be(a.j,function(b){var c=vd(a.f);Je(b.target)&&(ff(a,b),vd(a.f)&&!c&&bf(a))},"GET")},gf=function(a){Be(a.j,function(b){return ff(a,b)},"GET")},ff=function(a,b){b=b.target;try{var c=b.a?b.a.responseText:""}catch(d){c=""}a.l.set(a.F,c,a.w,"/",a.c)};
af.prototype.i=function(){for(var a=ea(this.H),b=a.next();!b.done;b=a.next()){b=b.value;var c=n(b,1);if(c){c=window.document.querySelectorAll(c);for(var d=0;d<c.length;d++)if(1==n(b,2)){var e=c[d];e&&e.parentNode&&e.parentNode.removeChild(e)}}}};af.prototype.u=function(){me(this.a)?null!=this.b&&(p.clearTimeout(this.b),this.b=null):df(this)};
var df=function(a){a.g||(ef(a,1),a.g=!0);null==a.b&&(a.b=ve(a.C,1E3,a))},ef=function(a,b){var c=new k(a.D);c.a.set("pageviewid",a.G);c.a.set("refererurl",p.location.href);c.a.set("type",b);Be(c,1==b?function(b){Je(b.target)||gf(a)}:null,"POST")};af.prototype.C=function(){ef(this,2);be(this.a,"visibilitychange",this.u,!1,this)};
(function(a,b){sa(a,function(c){for(var d=[],e=0;e<arguments.length;++e)d[e]=arguments[e];sa(a,u);b.apply(null,d)})})("__906a641ff040__",function(a){a=gb(a);a=new zd(a?JSON.parse(a):null);(new af(a)).start()});
}catch(e){_._DumpException(e)}
}).call(this,this.content_ads_contributor_ContributorTargetingClientJs);
// Google Inc.

//# sourceURL=/_/mss/boq-content-ads-contributor/_/js/k=boq-content-ads-contributor.ContributorTargetingClientJs.es.zrv6MFd0V00.O/rt=j/d=1/rs=AJlcJMwHD2ZibhP63nSNx71NAaYKnKk8UA/m=contributor
window.__906a641ff040__('W1siQ1VJRCIsMjAwLDMsIkFRQUIiLCJ4akQrM24vMmRnOWY1VUZBSVVmKzR2aFpHUVNjM0VLaGRldHdhMjdkVjBMTGI3WmF6N3dCRi9TWGd0Tkw4MGZqdHlzK3BqZ2E1Y1oraFRneGlESGJKazZZc1hkdm4zUkZqQzBub3V4aHoraWwrcWxCcElHSkVUbmFDeEZ0ZFFxWjZ3VnR1ZVE2NGtZN0JDTFhkcGs3ZmJIZndXYTJnT2FmRTRjVmduNVh0ekVubWlMSExRSE0rN1RVL2lyQnhMcCtLa0NSSmxSV2t0c09Vc2VsZnRsZGFUbzQzUWc4Rk5acVBZbjJaUy9aMjEvMWREdThJaDVHU0NNSVVMNTNnclJYQ0ticWg4b1N1akpiQ1RjQlFYMW9XUVc3eWQvRlNUdDlmRDhHSDg1TFVsa2h0d1hCZHFyZGtnMm9UVkRxeGpYR3dac2Y2QWZMYjNJNDJPdllZakpIbVFcdTAwM2RcdTAwM2QiLCIyNTAyMjlmMjAyNGE2YzdiIiwicmVmY29uIiw5MDAwMDAsNjAwMDAsNjAwMDAsODY0MDAwMDAsIlAsMTUzOTQyOTA2MjU5NDpBTEhHTHVRQUFBQVBVQ3d4TlRNNU5ESTVNRFl5TlRrMHVXdFlhcTRLcDhSempSTGlUcnpKZDFJNGJaK1NOZ1RZcjJjVVIzbDRxc251NHlCY29LSzZaa1F5ZnRnWE54WDB6YjhyalEwNUE5RTFwT2lmNXJTVFRoaVlQTzREcGZsaXpsQnlGZi9iNUFIeGhWTlRPK1Ura3BweFQrMDdUL2c4QUY5b3BoMXpMclhJbmh1RGt6cFRwMVBoYXBrczRubWxURXJvcUI2Ny91VlF1bFdYT29uQkJkTGtzVTNYaDB5QnNPdjMyNXNYZjhGNVhMSmQ2VFRPYW9xWkoyZk1BelBqQTM3NXZBN1RiU2FuMjFYTnhGRk9Yek1FN2FRY2JZWCswWkhoK1U1VGtMNVJqNHhYWFE2Q2o0N1hISWZtMlhNT3F1T0JsVSt1WGNwSmRWREtHRVl3a0VZYjI2WU0wTUNZQ2ZONGgyRE54R2pkOWtFdFRNQ0hhd1x1MDAzZFx1MDAzZCIsMjU5MjAwMF0KLFtbImFjY3V3ZWF0aGVyLmNvbSIsWyIyNTAyMjlmMjAyNGE2YzdiIiwiNDRkYTFhNWViZjdjN2E3OSJdCl0KLFsic2hvcGhvdXNlb2Z2YWdhYm9uZHMuY29tIixbIjI1MDIyOWYyMDI0YTZjN2IiLCIzOGVlZTAxY2M5YmUwYzUzIl0KXQpdCixbW1siaWZyYW1lW2lkXlx1MDAzZFwiZ29vZ2xlX2Fkc19pZnJhbWVcIl0iLDFdCixbIiN0b3AiLDFdCixbImRpdltpZF5cdTAwM2RcImdvb2dsZV9hZHNfaWZyYW1lX1wiXSIsMV0KLFsiLnBhbmVsLWFkLW1yIiwxXQosWyIjaGVhZGVyLWRhdmVrIiwxXQosWyIuYWRzYnlnb29nbGUiLDFdCixbIi5sb2dvLWFkIiwxXQosWyIjYWFkVG9wMzAwIiwxXQpdCl0KLCJodHRwczovL2NvbnRyaWJ1dG9yLmdvb2dsZS5jb20vc2NyaXB0cyJdCg\x3d\x3d');